# -*- coding: utf-8 -*-
"""GISACT_Next Assassement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iFc-EnOGs-dwRXrKZ8juu5BUZ34ubME-

**"PENGECEKAN DATA BUILDING FOOTPRITNT & ENERGI"**
"""

!pip install -q earthengine-api
!pip install -q geemap

# Pastikan sudah terinstall: !pip install geemap
import ee
import geemap
from google.colab import drive
import json

# 1. Autentikasi dan Inisialisasi
# Jika sudah pernah autentikasi di sesi sebelumnya, bisa langsung ee.Initialize()
ee.Authenticate()
ee.Initialize(project='ee-khairunnisafarah06')

# 2. Mount Drive untuk akses GeoJSON
drive.mount('/content/drive')

# ==========================================
# 2. Panggil Area Kajian (AOI) dari Assets
# ==========================================
# Ganti dengan path Aset yang baru Anda unggah di GEE Code Editor
# Formatnya: projects/nama-project-anda/assets/nama-aset-anda
path_asset_anda = 'projects/ee-khairunnisafarah06/assets/BF_GISACT'
roi = ee.FeatureCollection(path_asset_anda)

print("Aset Area Kajian berhasil dimuat!")

# 3. Memanggil Dataset (GHI, DNI, GTI)
assets = {
    'GHI': ee.Image("projects/sat-io/open-datasets/global_solar_atlas/ghi_LTAy_AvgDailyTotals"),
    'DNI': ee.Image("projects/sat-io/open-datasets/global_solar_atlas/dni_LTAy_AvgDailyTotals"),
    'GTI': ee.Image("projects/sat-io/open-datasets/global_solar_atlas/gti_LTAy_AvgDailyTotals")
}

# 4. Visualisasi
Map = geemap.Map()
Map.centerObject(roi, zoom=10)
Map.addLayer(roi, {'color': 'red'}, 'Batas AOI')

vis_params = {'min': 0, 'max': 8, 'palette': ['blue', 'green', 'yellow', 'red']}

for name, img in assets.items():
    # Clip dan tampilkan
    data_clipped = img.clip(roi)
    Map.addLayer(data_clipped, vis_params, name)
    print(f"Layer {name} berhasil dimuat.")

Map

"""**"PENGHITUNGAN POTENSI SOLAR PV"**"""

# ==========================================================
# SOLAR PV POTENTIAL INDEX
# ==========================================================
# -----------------------------------------------------
# CELL A — Install tambahan & import
# -----------------------------------------------------
# !pip install -q geopandas

import geopandas as gpd
import pandas as pd
import numpy as np
import ee
import geemap

# -----------------------------------------------------
# CELL B — Load footprint bangunan
# -----------------------------------------------------
# Ganti path sesuai lokasi file di Drive kamu.
# Bisa .geojson, .shp (dalam folder zip), atau GeoJSON hasil export dari GEE asset.

BUILDING_PATH = "/content/drive/MyDrive/GISACT/Building_Footprint.geojson"

buildings = gpd.read_file(BUILDING_PATH)

if buildings.crs is None:
    buildings = buildings.set_crs("EPSG:4326")
buildings = buildings.to_crs("EPSG:4326")
buildings["building_id"] = range(len(buildings))

# Tinggi bangunan: pakai kolom 'height' jika ada, default 10 m
if "height" not in buildings.columns:
    buildings["height"] = 10.0
else:
    buildings["height"] = pd.to_numeric(buildings["height"], errors="coerce").fillna(10.0)

# Hitung luas atap (proyeksikan ke CRS meter dulu agar akurat)
# Sesuaikan UTM zone dengan lokasi studi kamu (contoh: 32748/32749 untuk Jawa/Bali)
UTM_CRS = "EPSG:32749"
buildings_m = buildings.to_crs(UTM_CRS)
buildings["roof_area_m2"] = buildings_m.geometry.area
buildings["centroid_lon"] = buildings.geometry.centroid.x
buildings["centroid_lat"] = buildings.geometry.centroid.y

print(f"Bangunan dimuat: {len(buildings)} | luas atap rata-rata: {buildings['roof_area_m2'].mean():.1f} m2")

# -----------------------------------------------------
# CELL C — Konversi bangunan ke ee.FeatureCollection
# -----------------------------------------------------
# Diperlukan agar bisa pakai sampleRegions/reduceRegions di GEE.

buildings_fc = geemap.geopandas_to_ee(buildings[["building_id", "geometry"]])
print("Bangunan berhasil dikonversi ke ee.FeatureCollection.")

# -----------------------------------------------------
# CELL D — Tambahkan Cloud Fraction (untuk shading)
# -----------------------------------------------------
# CATATAN: dataset MODIS/061/MOD06_L2 sudah tidak tersedia/diakses
# (bukan MODIS asset publik biasa). Sebagai gantinya, Cloud Fraction
# dihitung dari Sentinel-2 Cloud Probability (s2cloudless), yang
# resolusinya lebih tinggi (~10-20 m, jauh lebih cocok untuk skala
# bangunan) dan tetap publik & stabil di GEE.
#
# Cloud_Probability bernilai 0-100 (%) -> dikonversi ke fraksi 0-1
# agar konsisten dengan asumsi shading model di Cell 1.1.

s2_clouds = (
    ee.ImageCollection("COPERNICUS/S2_CLOUD_PROBABILITY")
    .filterBounds(roi)
    .filterDate("2023-01-01", "2024-01-01")
    .select("probability")
    .mean()
    .divide(100)        # 0-100 -> 0-1
    .rename("CF")
    .clip(roi)
)

cloud_fraction = s2_clouds

# Stack semua image yang mau diekstrak ke bangunan
stack = (
    assets["GHI"].rename("GHI")
    .addBands(assets["DNI"].rename("DNI"))
    .addBands(assets["GTI"].rename("GTI"))
    .addBands(cloud_fraction.clip(roi))
)

# -----------------------------------------------------
# CELL E — Ekstrak nilai raster ke setiap bangunan (BATCH)
# -----------------------------------------------------
# PENTING: reduceRegions().getInfo() menarik SEMUA geometri + hasil sekaligus
# ke client. Untuk bangunan dalam jumlah besar ini gampang melebihi limit
# payload GEE (10 MB). Solusi: proses per-batch (mis. 200-500 bangunan/batch),
# dan getInfo() hanya properti penting (bukan geometri penuh).

# scale disesuaikan dengan resolusi terkasar di antara layer (Cloud Fraction ~1km),
# tapi GHI/DNI/GTI dari Global Solar Atlas biasanya ~250m, jadi scale=250 cukup wajar.

BATCH_SIZE = 1000

def extract_stack_to_buildings(buildings_gdf, stack_image, scale=250, batch_size=BATCH_SIZE):
    """
    Ekstrak nilai raster (mean per polygon) ke setiap bangunan secara batch,
    untuk menghindari GEE payload limit error.
    """
    n = len(buildings_gdf)
    all_rows = []

    for start in range(0, n, batch_size):
        end = min(start + batch_size, n)
        batch_gdf = buildings_gdf.iloc[start:end][["building_id", "geometry"]]

        # Convert hanya batch ini ke ee.FeatureCollection
        batch_fc = geemap.geopandas_to_ee(batch_gdf)

        sampled_batch = stack_image.reduceRegions(
            collection=batch_fc,
            reducer=ee.Reducer.mean(),
            scale=scale,
            tileScale=4,   # naikkan tileScale agar komputasi server lebih ringan per request
        )

        # Hanya ambil properti (building_id + hasil reduce), BUKAN geometri,
        # supaya payload getInfo() jauh lebih kecil.
        sampled_props = sampled_batch.select(
            propertySelectors=["building_id"] + stack_image.bandNames().getInfo(),
            retainGeometry=False,
        )

        try:
            batch_info = sampled_props.getInfo()
        except ee.EEException as e:
            print(f"   ⚠️ Batch {start}-{end} gagal ({e}), mencoba batch lebih kecil...")
            # Fallback: pecah batch ini jadi dua, proses ulang rekursif
            half = max(1, (end - start) // 2)
            sub1 = extract_stack_to_buildings(
                buildings_gdf.iloc[start:start+half], stack_image, scale, batch_size=half
            )
            sub2 = extract_stack_to_buildings(
                buildings_gdf.iloc[start+half:end], stack_image, scale, batch_size=half
            )
            all_rows.extend(sub1.to_dict("records"))
            all_rows.extend(sub2.to_dict("records"))
            continue

        for feat in batch_info["features"]:
            all_rows.append(feat["properties"])

        print(f"   Batch {start}-{end} selesai ({len(batch_info['features'])} bangunan).")

    return pd.DataFrame(all_rows)


print(f"Memulai ekstraksi raster ke {len(buildings)} bangunan dalam batch ukuran {BATCH_SIZE}...")
df_sat = extract_stack_to_buildings(buildings, stack, scale=250, batch_size=BATCH_SIZE)

print("Contoh hasil ekstraksi raster ke bangunan:")
print(df_sat.head())
print(f"Total bangunan berhasil diekstrak: {len(df_sat)} / {len(buildings)}")

# Gabungkan kembali ke GeoDataFrame bangunan berdasarkan building_id
buildings = buildings.merge(
    df_sat[["building_id", "GHI", "DNI", "GTI", "CF"]],
    on="building_id",
    how="left",
)

# Isi nilai kosong (misal bangunan di tepi AOI tanpa piksel valid) dengan median
for col in ["GHI", "DNI", "GTI", "CF"]:
    buildings[col] = buildings[col].fillna(buildings[col].median())

print("\nStatistik irradiance & cloud fraction per bangunan:")
print(buildings[["GHI", "DNI", "GTI", "CF"]].describe().round(3))

# ==========================================================
# PERHITUNGAN POTENSI ENERGI SURYA PER BANGUNAN/ATAP
# ==========================================================

# --- Estimasi area atap potensial (kemiringan & orientasi) ---
# Tanpa data DEM/DSM detail, gunakan asumsi rasio luas atap yang
# benar-benar bisa dipasang panel (mempertimbangkan kemiringan,
# orientasi, dan obstruksi seperti tangga atap/AC/ventilasi).
ROOF_USABLE_RATIO = 0.70   # 70% dari luas footprint

buildings["roof_effective_m2"] = buildings["roof_area_m2"] * ROOF_USABLE_RATIO

# --- Shading sederhana (height & Cloud Fraction) ---
# height_factor : bangunan lebih tinggi -> atap lebih terbuka -> shading factor mendekati 1
# cf_factor     : cloud fraction lebih tinggi -> radiasi efektif berkurang

h_min, h_max = buildings["height"].min(), buildings["height"].max()
if h_max > h_min:
    height_factor = 0.85 + 0.15 * (buildings["height"] - h_min) / (h_max - h_min)
else:
    height_factor = pd.Series(0.90, index=buildings.index)

# CF biasanya 0-1 (fraksi tutupan awan). Faktor reduksi: makin tinggi CF, makin besar reduksi.
cf_factor = 1 - (buildings["CF"].clip(0, 1) * 0.3)   # maksimum reduksi 30% akibat awan

buildings["shading_factor"] = height_factor * cf_factor

# --- Model energi PV (pakai GTI jika tersedia, lebih representatif untuk panel miring) ---
# GTI = Global Tilted Irradiance (kWh/m2/hari) -> lebih akurat dibanding GHI untuk panel ber-tilt
buildings["irradiance_kwh_m2_day"] = buildings["GTI"]
buildings["irradiance_kwh_m2_year"] = buildings["irradiance_kwh_m2_day"] * 365

print("\nPotensi energi surya per bangunan -> selesai dihitung.")

# ==========================================================
# PERHITUNGAN DAYA & ENERGI
# ==========================================================

PANEL_EFFICIENCY  = 0.20    # efisiensi panel 20%
PERFORMANCE_RATIO = 0.80    # performance ratio sistem 80%
PANEL_POWER_WP    = 400     # watt-peak per panel
PANEL_AREA_M2     = 2.0     # luas per panel (m2)

# --- Estimasi kapasitas terpasang (kWp) ---
buildings["n_panels"] = np.floor(buildings["roof_effective_m2"] / PANEL_AREA_M2).astype(int)
buildings["capacity_kwp"] = buildings["n_panels"] * PANEL_POWER_WP / 1000.0

# --- Estimasi produksi energi tahunan (kWh/tahun) ---
# E = Irradiance_tahunan x Luas_atap_efektif x efisiensi_panel x PR x shading_factor
buildings["energy_kwh_yr"] = (
    buildings["irradiance_kwh_m2_year"]
    * buildings["roof_effective_m2"]
    * PANEL_EFFICIENCY
    * PERFORMANCE_RATIO
    * buildings["shading_factor"]
)

print("\n[1.2] Kapasitas & produksi energi -> selesai dihitung.")
print(buildings[["building_id", "roof_area_m2", "capacity_kwp", "energy_kwh_yr"]].describe().round(2))

# ==========================================================
# NORMALISASI INDEKS (MIN-MAX SCALING 0-1) + KLASIFIKASI
# ==========================================================

# Gunakan densitas energi per m2 atap efektif agar bangunan besar & kecil
# bisa dibandingkan secara adil (bukan total energi mentah).
buildings["pv_density"] = buildings["energy_kwh_yr"] / (buildings["roof_effective_m2"] + 1e-9)

mn, mx = buildings["pv_density"].min(), buildings["pv_density"].max()
buildings["pv_index"] = (buildings["pv_density"] - mn) / (mx - mn + 1e-9)

buildings["pv_class"] = pd.cut(
    buildings["pv_index"],
    bins=[-0.001, 0.333, 0.667, 1.001],
    labels=["Rendah", "Sedang", "Tinggi"],
)

print("\nSolar PV Potential Index (0-1) -> selesai.")
print(buildings[["building_id", "pv_index", "pv_class"]].describe(include="all").round(3))

# ==========================================================
# OUTPUT 1 — SOLAR PV POTENTIAL INDEX
# ==========================================================

output_cols = [
    "building_id", "centroid_lon", "centroid_lat",
    "roof_area_m2", "roof_effective_m2", "height",
    "GHI", "DNI", "GTI", "CF",
    "shading_factor", "capacity_kwp", "energy_kwh_yr",
    "pv_density", "pv_index", "pv_class", "geometry",
]
output_cols = [c for c in output_cols if c in buildings.columns]
output1 = buildings[output_cols]

# Simpan hasil
output1.to_file("/content/drive/MyDrive/GISACT/output1_solar_pv_index.geojson", driver="GeoJSON")
output1.drop(columns="geometry").to_csv("/content/drive/MyDrive/GISACT/output1_solar_pv_index.csv", index=False)

print("\n✅ OUTPUT 1 tersimpan:")
print("   - /content/drive/MyDrive/GISACT/output1_solar_pv_index.geojson")
print("   - /content/drive/MyDrive/GISACT/output1_solar_pv_index.csv")
print(f"\nDistribusi klasifikasi: \n{buildings['pv_class'].value_counts()}")

# ==========================================================
# CELL F — Visualisasi hasil dengan matplotlib
# ==========================================================

import matplotlib.pyplot as plt
import matplotlib.colors as mcolors

fig, axes = plt.subplots(1, 2, figsize=(16, 7))

# ---- Peta 1: Solar PV Potential Index ----
ax = axes[0]
output1.plot(
    column="pv_index",
    cmap="YlOrRd",
    linewidth=0.3,
    edgecolor="black",
    legend=True,
    legend_kwds={"label": "PV Index (0-1)", "shrink": 0.7},
    ax=ax,
)
ax.set_title("Solar PV Potential Index per Bangunan")
ax.set_xlabel("Longitude")
ax.set_ylabel("Latitude")

# ---- Peta 2: Klasifikasi Rendah/Sedang/Tinggi ----
ax2 = axes[1]
class_colors = {"Rendah": "#3B82C4", "Sedang": "#F2A623", "Tinggi": "#D85A30"}
output1["color"] = output1["pv_class"].map(class_colors)

output1.plot(
    color=output1["color"],
    linewidth=0.3,
    edgecolor="black",
    ax=ax2,
)
ax2.set_title("Klasifikasi Solar PV Potential")
ax2.set_xlabel("Longitude")
ax2.set_ylabel("Latitude")

# Legend manual untuk peta klasifikasi
from matplotlib.patches import Patch
legend_elements = [Patch(facecolor=color, edgecolor="black", label=label)
                    for label, color in class_colors.items()]
ax2.legend(handles=legend_elements, loc="upper right", title="Kelas")

plt.tight_layout()
plt.savefig("/content/drive/MyDrive/GISACT/output1_pv_map.png", dpi=150, bbox_inches="tight")
plt.show()

print("✅ Peta tersimpan: /content/drive/MyDrive/GISACT/output1_pv_map.png")

# ---- Statistik ringkas ----
print("\n📊 Ringkasan Solar PV Potential Index:")
print(output1["pv_class"].value_counts())
print(f"\nRata-rata pv_index: {output1['pv_index'].mean():.3f}")
print(f"Total kapasitas terpasang: {output1['capacity_kwp'].sum():,.1f} kWp")
print(f"Total produksi energi tahunan: {output1['energy_kwh_yr'].sum():,.0f} kWh/tahun")

"""**"PENGHITUNGAN ESTIMASI NILAI EKONOMI BANGUNAN"**"""

# ==========================================================
# TASK 2 — ESTIMASI NILAI EKONOMI BANGUNAN
# ==========================================================
# Prasyarat dari Task 1 yang sudah ada di memori:
#   - buildings (GeoDataFrame): building_id, geometry, roof_area_m2,
#     height, centroid_lon, centroid_lat, dst.
#   - roi (ee.FeatureCollection) -> dipakai untuk batas AOI saat query OSM
#
# Langkah:
#   2.1  Rekayasa fitur (jarak ke anchor ekonomi, jalan, hierarki jalan,
#        luas & tinggi, fungsi, kepadatan, aksesibilitas, transportasi/POI)
#   2.2  Estimasi nilai ekonomi relatif (regresi ML) + grafik regresi
#   2.3  Normalisasi -> Economic Value Index (0-1) + klasifikasi
# ==========================================================

# -----------------------------------------------------
# CELL A — Install & import tambahan
# -----------------------------------------------------
!pip install -q osmnx scikit-learn

import osmnx as ox
import numpy as np
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score, mean_absolute_error
import matplotlib.pyplot as plt

UTM_CRS = "EPSG:32749"   # samakan dengan UTM zone yang dipakai di Task 1

# ==========================================================
# PENGAMBILAN DATA DARI OSM
# ==========================================================

print("Mengambil data jalan & POI dari OpenStreetMap...")

# --- Tentukan area query OSM dari bounding box bangunan + buffer ---
bounds = buildings.total_bounds  # [minx, miny, maxx, maxy]
center_lat = (bounds[1] + bounds[3]) / 2
center_lon = (bounds[0] + bounds[2]) / 2

# Radius query: dari diagonal bounding box + buffer 1.5 km, dibatasi wajar (max 10 km)
import math
diag_km = math.hypot(bounds[2] - bounds[0], bounds[3] - bounds[1]) * 111  # derajat -> km kasar
query_radius_m = min(max(diag_km * 1000 / 2 + 1500, 1500), 10000)

# -----------------------------------------------------
# 2.1.a — Jaringan jalan & hierarki jalan
# -----------------------------------------------------
try:
    G = ox.graph_from_point((center_lat, center_lon), dist=query_radius_m, network_type="drive")
    edges = ox.graph_to_gdfs(G, nodes=False).to_crs(UTM_CRS)
    edges["highway"] = edges["highway"].astype(str)
    print(f"   ✅ Jaringan jalan: {len(edges)} ruas jalan dimuat.")
except Exception as e:
    print(f"   ⚠️ OSM jalan gagal ({e}), pakai data dummy.")
    edges = gpd.GeoDataFrame(geometry=[], crs=UTM_CRS)

# Hierarki jalan: bobot kepentingan (lebih tinggi = jalan lebih utama)
ROAD_HIERARCHY_WEIGHT = {
    "motorway": 1.0, "trunk": 0.9, "primary": 0.8,
    "secondary": 0.6, "tertiary": 0.4, "residential": 0.2,
    "unclassified": 0.15, "service": 0.1,
}

def road_weight(highway_val):
    """Ambil bobot hierarki tertinggi jika highway berisi list string."""
    if "[" in highway_val:  # contoh: "['primary', 'secondary']"
        types = highway_val.strip("[]").replace("'", "").split(", ")
    else:
        types = [highway_val]
    weights = [ROAD_HIERARCHY_WEIGHT.get(t, 0.1) for t in types]
    return max(weights) if weights else 0.1

if len(edges) > 0:
    edges["road_weight"] = edges["highway"].apply(road_weight)
    main_roads = edges[edges["road_weight"] >= 0.6]   # primary ke atas dianggap "jalan utama"
else:
    main_roads = edges

# -----------------------------------------------------
# 2.1.b — Anchor ekonomi & POI (pusat bisnis, retail, transportasi)
# -----------------------------------------------------
try:
    tags_anchor = {
        "shop": True,
        "amenity": ["marketplace", "bank", "mall", "fuel"],
        "office": True,
        "landuse": ["commercial", "retail"],
    }
    anchors = ox.features_from_point((center_lat, center_lon), tags=tags_anchor, dist=query_radius_m)
    anchors = anchors[anchors.geometry.type.isin(["Point", "Polygon", "MultiPolygon"])].copy()
    anchors["geometry"] = anchors.geometry.centroid
    anchors = anchors.to_crs(UTM_CRS)
    print(f"   ✅ Anchor ekonomi: {len(anchors)} titik dimuat.")
except Exception as e:
    print(f"   ⚠️ OSM anchor ekonomi gagal ({e}), pakai data kosong.")
    anchors = gpd.GeoDataFrame(geometry=[], crs=UTM_CRS)

try:
    tags_transit = {
        "highway": "bus_stop",
        "railway": ["station", "halt"],
        "amenity": "bus_station",
    }
    transit = ox.features_from_point((center_lat, center_lon), tags=tags_transit, dist=query_radius_m)
    transit["geometry"] = transit.geometry.centroid
    transit = transit.to_crs(UTM_CRS)
    print(f"   ✅ Titik transportasi publik: {len(transit)} titik dimuat.")
except Exception as e:
    print(f"   ⚠️ OSM transit gagal ({e}), pakai data kosong.")
    transit = gpd.GeoDataFrame(geometry=[], crs=UTM_CRS)

# -----------------------------------------------------
# 2.1.c — Hitung fitur jarak & kepadatan per bangunan
# -----------------------------------------------------
buildings_m = buildings.to_crs(UTM_CRS).copy()
centroids = buildings_m.geometry.centroid

def min_distance_to(centroids_series, target_gdf, default_val):
    """Jarak minimum dari tiap centroid bangunan ke geometri terdekat di target_gdf."""
    if len(target_gdf) == 0:
        return pd.Series(default_val, index=centroids_series.index)
    target_union = target_gdf.geometry.unary_union
    return centroids_series.distance(target_union)

print("Menghitung fitur jarak & kepadatan...")

buildings["dist_anchor_m"] = min_distance_to(centroids, anchors, default_val=query_radius_m)
buildings["dist_main_road_m"] = min_distance_to(centroids, main_roads, default_val=query_radius_m)
buildings["dist_any_road_m"] = min_distance_to(centroids, edges, default_val=query_radius_m)
buildings["dist_transit_m"] = min_distance_to(centroids, transit, default_val=query_radius_m)

# Hierarki jalan terdekat (ambil road_weight dari ruas jalan terdekat)
if len(edges) > 0:
    nearest_idx = edges.geometry.sindex.nearest(centroids.geometry, return_all=False)
    buildings["road_hierarchy"] = edges.iloc[nearest_idx[1]]["road_weight"].values
else:
    buildings["road_hierarchy"] = 0.1

# Kepadatan bangunan sekitar (buffer 200 m)
buf200 = centroids.buffer(200)
buildings["neighbor_density"] = [
    buildings_m[buildings_m.geometry.intersects(b)].shape[0] - 1
    for b in buf200
]

# Aksesibilitas gabungan (indeks sederhana: makin dekat ke jalan & transit, makin tinggi)
buildings["accessibility_index"] = (
    1 / (1 + buildings["dist_main_road_m"] / 500)
    + 1 / (1 + buildings["dist_transit_m"] / 500)
) / 2

# -----------------------------------------------------
# 2.1.d — Fungsi/okupansi bangunan
# -----------------------------------------------------
if "building" not in buildings.columns:
    buildings["building"] = "yes"

FUNC_SCORE_MAP = {
    "commercial": 1.0, "retail": 0.95, "office": 0.9, "supermarket": 0.95,
    "industrial": 0.7, "mixed": 0.8, "hotel": 0.85,
    "residential": 0.5, "house": 0.45, "apartments": 0.55, "yes": 0.5,
}
buildings["func_score"] = buildings["building"].map(FUNC_SCORE_MAP).fillna(0.5)

print("\nRingkasan fitur:")
feature_cols = [
    "roof_area_m2", "height", "dist_anchor_m", "dist_main_road_m",
    "road_hierarchy", "neighbor_density", "accessibility_index",
    "dist_transit_m", "func_score",
]
print(buildings[feature_cols].describe().round(2))

# ==========================================================
# 2.2  ESTIMASI NILAI EKONOMI RELATIF (REGRESI)
# ==========================================================
# CATATAN PENTING:
# Tidak ada data harga/nilai ekonomi riil sebagai target (ground truth),
# jadi regresi di sini bersifat "proxy-based": kita membuat target sintetis
# (economic_proxy) dari kombinasi berbobot fitur yang secara teori berkorelasi
# dengan nilai ekonomi (dekat jalan utama, dekat anchor, fungsi komersial, dst),
# lalu melatih model regresi untuk mempelajari & menghaluskan relasi antar fitur.

def minmax(s):
    return (s - s.min()) / (s.max() - s.min() + 1e-9)

# --- Target sintetis (proxy) berbasis teori ekonomi spasial ---
buildings["economic_proxy"] = (
    0.25 * (1 - minmax(buildings["dist_anchor_m"]))
    + 0.20 * (1 - minmax(buildings["dist_main_road_m"]))
    + 0.15 * minmax(buildings["road_hierarchy"])
    + 0.15 * minmax(buildings["accessibility_index"])
    + 0.10 * minmax(buildings["neighbor_density"])
    + 0.15 * buildings["func_score"]
) * 100   # skala 0-100 agar mirip "indeks nilai lahan"

# --- Siapkan fitur (X) & target (y) ---
X_cols = [
    "roof_area_m2", "height", "dist_anchor_m", "dist_main_road_m",
    "road_hierarchy", "neighbor_density", "accessibility_index",
    "dist_transit_m", "func_score",
]
X = buildings[X_cols].fillna(buildings[X_cols].median())
y = buildings["economic_proxy"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_test_s = scaler.transform(X_test)
X_all_s = scaler.transform(X)

# --- Model: Random Forest Regressor (menangkap relasi non-linear antar fitur) ---
model = RandomForestRegressor(n_estimators=300, max_depth=8, random_state=42, n_jobs=-1)
model.fit(X_train_s, y_train)

y_pred_test = model.predict(X_test_s)
y_pred_all = model.predict(X_all_s)

r2 = r2_score(y_test, y_pred_test)
mae = mean_absolute_error(y_test, y_pred_test)

print(f"\nModel regresi (Random Forest) -> R2 test: {r2:.3f} | MAE: {mae:.2f}")

buildings["econ_value_pred"] = y_pred_all

# --- Feature importance ---
importances = pd.Series(model.feature_importances_, index=X_cols).sort_values(ascending=False)
print("\nFeature importance:")
print(importances.round(3))

# -----------------------------------------------------
# GRAFIK REGRESI (2.2)
# -----------------------------------------------------
fig, axes = plt.subplots(1, 3, figsize=(20, 6))

# --- Grafik 1: Actual vs Predicted (scatter + garis ideal) ---
ax = axes[0]
ax.scatter(y_test, y_pred_test, alpha=0.5, color="#1D9E75", edgecolor="black", linewidth=0.3)
lims = [min(y_test.min(), y_pred_test.min()), max(y_test.max(), y_pred_test.max())]
ax.plot(lims, lims, "--", color="#D85A30", linewidth=1.5, label="Garis ideal (y=x)")
ax.set_xlabel("Nilai Ekonomi Aktual (proxy)")
ax.set_ylabel("Nilai Ekonomi Prediksi")
ax.set_title(f"Actual vs Predicted\nR2 = {r2:.3f} | MAE = {mae:.2f}")
ax.legend()
ax.grid(alpha=0.2)

# --- Grafik 2: Feature Importance (bar chart) ---
ax = axes[1]
importances_sorted = importances.sort_values(ascending=True)
colors_bar = plt.cm.YlOrRd(np.linspace(0.3, 0.9, len(importances_sorted)))
ax.barh(importances_sorted.index, importances_sorted.values, color=colors_bar)
ax.set_xlabel("Feature Importance")
ax.set_title("Kontribusi Fitur dalam Model")
ax.grid(axis="x", alpha=0.2)

# --- Grafik 3: Residual plot ---
ax = axes[2]
residuals = y_test - y_pred_test
ax.scatter(y_pred_test, residuals, alpha=0.5, color="#378ADD", edgecolor="black", linewidth=0.3)
ax.axhline(0, color="#D85A30", linestyle="--", linewidth=1.5)
ax.set_xlabel("Nilai Prediksi")
ax.set_ylabel("Residual (Aktual - Prediksi)")
ax.set_title("Residual Plot")
ax.grid(alpha=0.2)

plt.tight_layout()
plt.savefig("/content/drive/MyDrive/GISACT/output2_regression_plots.png", dpi=150, bbox_inches="tight")
plt.show()

print("✅ Grafik regresi tersimpan: /content/drive/MyDrive/GISACT/output2_regression_plots.png")

# ==========================================================
# 2.3  NORMALISASI INDEKS (MIN-MAX SCALING 0-1) + KLASIFIKASI
# ==========================================================

buildings["econ_index"] = minmax(buildings["econ_value_pred"])

buildings["econ_class"] = pd.cut(
    buildings["econ_index"],
    bins=[-0.001, 0.333, 0.667, 1.001],
    labels=["Rendah", "Sedang", "Tinggi"],
)

print("\n[2.3] Economic Value Index (0-1) -> selesai.")
print(buildings[["building_id", "econ_index", "econ_class"]].describe(include="all").round(3))
print(f"\nDistribusi klasifikasi:\n{buildings['econ_class'].value_counts()}")

# ==========================================================
# OUTPUT 2 — ECONOMIC VALUE INDEX
# ==========================================================

output2_cols = [
    "building_id", "centroid_lon", "centroid_lat",
    "roof_area_m2", "height", "dist_anchor_m", "dist_main_road_m",
    "road_hierarchy", "neighbor_density", "accessibility_index",
    "dist_transit_m", "func_score",
    "economic_proxy", "econ_value_pred", "econ_index", "econ_class",
    "geometry",
]
output2_cols = [c for c in output2_cols if c in buildings.columns]
output2 = buildings[output2_cols]

output2.to_file("/content/drive/MyDrive/GISACT/output2_economic_index.geojson", driver="GeoJSON")
output2.drop(columns="geometry").to_csv("/content/drive/MyDrive/GISACT/output2_economic_index.csv", index=False)

print("\n✅ OUTPUT 2 tersimpan:")
print("   - /content/drive/MyDrive/GISACT/output2_economic_index.geojson")
print("   - /content/drive/MyDrive/GISACT/output2_economic_index.csv")

# ==========================================================
# CELL B — Visualisasi peta Economic Value Index (matplotlib)
# ==========================================================

fig, axes = plt.subplots(1, 2, figsize=(16, 7))

ax = axes[0]
output2.plot(
    column="econ_index",
    cmap="Blues",
    linewidth=0.3,
    edgecolor="black",
    legend=True,
    legend_kwds={"label": "Economic Index (0-1)", "shrink": 0.7},
    ax=ax,
)
ax.set_title("Economic Value Index per Bangunan")
ax.set_xlabel("Longitude")
ax.set_ylabel("Latitude")

ax2 = axes[1]
class_colors = {"Rendah": "#85B7EB", "Sedang": "#378ADD", "Tinggi": "#0C447C"}
output2["color"] = output2["econ_class"].map(class_colors)
output2.plot(color=output2["color"], linewidth=0.3, edgecolor="black", ax=ax2)
ax2.set_title("Klasifikasi Economic Value")
ax2.set_xlabel("Longitude")
ax2.set_ylabel("Latitude")

from matplotlib.patches import Patch
legend_elements = [Patch(facecolor=color, edgecolor="black", label=label)
                    for label, color in class_colors.items()]
ax2.legend(handles=legend_elements, loc="upper right", title="Kelas")

plt.tight_layout()
plt.savefig("/content/drive/MyDrive/GISACT/output2_economic_map.png", dpi=150, bbox_inches="tight")
plt.show()

print("✅ Peta tersimpan: /content/drive/MyDrive/GISACT/output2_economic_map.png")

"""**"PENYUNSUNAN VARIABEL LINGKUNGAN"**"""

# ==========================================================
# TASK 3 — PENYUSUNAN INDEKS DEGRADASI LINGKUNGAN
# (sambungan dari Task 1 & 2 - variabel 'buildings', 'roi' sudah tersedia)
# ==========================================================
# Prasyarat yang sudah ada di memori:
#   - buildings (GeoDataFrame): building_id, geometry, centroid_lon/lat, dst.
#   - roi (ee.FeatureCollection): batas AOI
#   - ee, geemap sudah di-import & ee.Initialize() sudah dijalankan
#
# Langkah:
#   3.1  Indikator lingkungan dari satelit: CF, AOD, LST, NDVI, NDBI, Land Cover
#   3.2  Normalisasi & agregasi -> Environmental Degradation Index (0-1)
# ==========================================================

import ee
import geemap
import pandas as pd
import numpy as np
import geopandas as gpd
import matplotlib.pyplot as plt
from matplotlib.patches import Patch

# Rentang tanggal observasi (sesuaikan dengan kebutuhan studi)
DATE_START = "2023-01-01"
DATE_END   = "2024-01-01"

# ==========================================================
# 3.1  INDIKATOR LINGKUNGAN DARI SATELIT
# ==========================================================

print("Menyiapkan indikator lingkungan dari satelit...")

# -----------------------------------------------------
# 3.1.a — Cloud Fraction (CF) -> Sentinel-2 Cloud Probability
# -----------------------------------------------------
# Sama seperti Task 1: MOD06_L2 tidak tersedia, jadi pakai s2cloudless
# yang resolusinya lebih halus (~10-20m) dan stabil diakses.

# -----------------------------------------------------
# 3.1.b — AOD (Aerosol Optical Depth) -> Sentinel-5P TROPOMI
# -----------------------------------------------------
# COPERNICUS/S5P/OFFL/L3_AER_AI memberikan UV Aerosol Index, proxy umum
# untuk AOD karena MODIS AOD (MOD04) resolusinya sangat kasar (~3-10km)
# dan kurang cocok untuk skala bangunan.

aod_img = (
    ee.ImageCollection("COPERNICUS/S5P/OFFL/L3_AER_AI")
    .filterBounds(roi)
    .filterDate(DATE_START, DATE_END)
    .select("absorbing_aerosol_index")
    .mean()
    .rename("AOD")
)

# -----------------------------------------------------
# 3.1.c — LST (Land Surface Temperature) -> MODIS MOD11A1
# -----------------------------------------------------
# Catatan: ini BUKAN MOD06, melainkan MOD11A1 (LST product), dataset
# berbeda yang stabil & publik. Band LST_Day_1km dalam satuan Kelvin*0.02.

lst_img = (
    ee.ImageCollection("MODIS/061/MOD11A1")
    .filterBounds(roi)
    .filterDate(DATE_START, DATE_END)
    .select("LST_Day_1km")
    .mean()
    .multiply(0.02)
    .subtract(273.15)   # Kelvin -> Celsius
    .rename("LST")
)

# -----------------------------------------------------
# 3.1.d — NDVI & NDBI -> Sentinel-2 Surface Reflectance
# -----------------------------------------------------

def mask_s2_clouds(image):
    """Mask awan sederhana memakai band SCL (Scene Classification Layer)."""
    scl = image.select("SCL")
    # Kelas SCL yang dianggap bersih: 4=vegetation, 5=bare soil, 6=water, 11=snow
    clear_mask = scl.eq(4).Or(scl.eq(5)).Or(scl.eq(6)).Or(scl.eq(11))
    return image.updateMask(clear_mask)

s2_sr = (
    ee.ImageCollection("COPERNICUS/S2_SR_HARMONIZED")
    .filterBounds(roi)
    .filterDate(DATE_START, DATE_END)
    .filter(ee.Filter.lt("CLOUDY_PIXEL_PERCENTAGE", 20))
    .map(mask_s2_clouds)
    .median()
)

ndvi_img = s2_sr.normalizedDifference(["B8", "B4"]).rename("NDVI")
ndbi_img = s2_sr.normalizedDifference(["B11", "B8"]).rename("NDBI")

# -----------------------------------------------------
# 3.1.e — Land Cover -> ESA WorldCover v200
# -----------------------------------------------------
# Kelas ESA WorldCover (kode): 10=Tree cover, 20=Shrubland, 30=Grassland,
# 40=Cropland, 50=Built-up, 60=Bare/sparse veg, 70=Snow/ice, 80=Water,
# 90=Wetland, 95=Mangroves, 100=Moss/lichen.
# Untuk indeks degradasi: Built-up & Bare/sparse dianggap kontribusi
# degradasi tinggi; Tree cover/Wetland/Water dianggap kontribusi rendah.

worldcover = ee.ImageCollection("ESA/WorldCover/v200").first().select("Map").rename("LC")

LC_DEGRADATION_SCORE = {
    10: 0.0,   # Tree cover -> tidak terdegradasi
    20: 0.2,   # Shrubland
    30: 0.2,   # Grassland
    40: 0.4,   # Cropland
    50: 1.0,   # Built-up -> degradasi tinggi
    60: 0.8,   # Bare/sparse vegetation
    70: 0.3,   # Snow/ice
    80: 0.0,   # Water
    90: 0.1,   # Wetland
    95: 0.0,   # Mangroves
    100: 0.3,  # Moss/lichen
}

# Buat image skor degradasi dari reclassify land cover
lc_score_img = worldcover.remap(
    list(LC_DEGRADATION_SCORE.keys()),
    list(LC_DEGRADATION_SCORE.values()),
    defaultValue=0.3,
).rename("LC_score")

print("✅ Semua indikator lingkungan (CF, AOD, LST, NDVI, NDBI, LC) siap diekstrak.")

# -----------------------------------------------------
# Stack semua band jadi satu image
# -----------------------------------------------------
env_stack = (
    cloud_fraction
    .addBands(aod_img)
    .addBands(lst_img)
    .addBands(ndvi_img)
    .addBands(ndbi_img)
    .addBands(lc_score_img)
    .clip(roi)
)

# ==========================================================
# CELL B — Ekstraksi nilai raster ke bangunan (BATCH, sama seperti Task 1)
# ==========================================================
# Reuse fungsi extract_stack_to_buildings() dari Task 1.
# Jika fungsi itu sudah ada di memori (Colab session), baris di bawah
# bisa langsung dipakai. Jika belum/sesi baru, definisikan ulang di sini.

BATCH_SIZE = 2000

def extract_stack_to_buildings(buildings_gdf, stack_image, scale=100, batch_size=BATCH_SIZE):
    """
    Ekstrak nilai raster (mean per polygon) ke setiap bangunan secara batch,
    untuk menghindari GEE payload limit error.
    """
    n = len(buildings_gdf)
    all_rows = []

    for start in range(0, n, batch_size):
        end = min(start + batch_size, n)
        batch_gdf = buildings_gdf.iloc[start:end][["building_id", "geometry"]]
        batch_fc = geemap.geopandas_to_ee(batch_gdf)

        sampled_batch = stack_image.reduceRegions(
            collection=batch_fc,
            reducer=ee.Reducer.mean(),
            scale=scale,
            tileScale=4,
        )

        sampled_props = sampled_batch.select(
            propertySelectors=["building_id"] + stack_image.bandNames().getInfo(),
            retainGeometry=False,
        )

        try:
            batch_info = sampled_props.getInfo()
        except ee.EEException as e:
            print(f"   ⚠️ Batch {start}-{end} gagal ({e}), mencoba batch lebih kecil...")
            half = max(1, (end - start) // 2)
            sub1 = extract_stack_to_buildings(
                buildings_gdf.iloc[start:start+half], stack_image, scale, batch_size=half
            )
            sub2 = extract_stack_to_buildings(
                buildings_gdf.iloc[start+half:end], stack_image, scale, batch_size=half
            )
            all_rows.extend(sub1.to_dict("records"))
            all_rows.extend(sub2.to_dict("records"))
            continue

        for feat in batch_info["features"]:
            all_rows.append(feat["properties"])

        print(f"   Batch {start}-{end} selesai ({len(batch_info['features'])} bangunan).")

    return pd.DataFrame(all_rows)


print(f"\nMemulai ekstraksi indikator lingkungan ke {len(buildings)} bangunan...")
df_env = extract_stack_to_buildings(buildings, env_stack, scale=100, batch_size=BATCH_SIZE)

print("Contoh hasil ekstraksi:")
print(df_env.head())
print(f"Total bangunan berhasil diekstrak: {len(df_env)} / {len(buildings)}")

# -----------------------------------------------------
# VALIDASI: pastikan semua band hasil ekstraksi benar-benar ada di df_env.
# Jika suatu band hilang total (mis. AOD kosong karena cakupan Sentinel-5P
# yang jarang di AOI tertentu), beri peringatan jelas & isi dengan nilai
# default 0 (bukan langsung KeyError yang membingungkan).
# -----------------------------------------------------
env_result_cols = ["CF", "AOD", "LST", "NDVI", "NDBI", "LC_score"]
missing_cols = [c for c in env_result_cols if c not in df_env.columns]

if missing_cols:
    print(f"\n⚠️ PERINGATAN: kolom berikut TIDAK ADA di hasil ekstraksi: {missing_cols}")
    print("   Kemungkinan penyebab: tidak ada citra yang menutupi AOI pada rentang")
    print("   tanggal tersebut (umum terjadi untuk Sentinel-5P AOD yang orbitnya jarang),")
    print("   atau nama band berubah. Mengisi kolom yang hilang dengan nilai 0.")
    for c in missing_cols:
        df_env[c] = 0.0

# Gabungkan kembali ke GeoDataFrame bangunan
# CATATAN: kolom 'CF' kemungkinan sudah ada dari Task 1 (Cloud Fraction
# untuk shading PV). Untuk menghindari MergeError karena duplikasi nama
# kolom, drop dulu kolom-kolom hasil Task 3 yang mungkin sudah ada
# sebelum merge ulang dari df_env.
buildings = buildings.drop(columns=[c for c in env_result_cols if c in buildings.columns])

buildings = buildings.merge(
    df_env[["building_id"] + env_result_cols],
    on="building_id",
    how="left",
)

# Isi nilai kosong dengan median (mis. bangunan di tepi AOI tanpa piksel valid).
# Jika SELURUH kolom kosong (median juga NaN), fallback ke 0 agar tidak
# meninggalkan NaN yang nanti merusak perhitungan minmax/agregasi.
for col in ["CF", "AOD", "LST", "NDVI", "NDBI", "LC_score"]:
    med = buildings[col].median()
    fill_val = med if pd.notna(med) else 0.0
    buildings[col] = buildings[col].fillna(fill_val)

print("\nStatistik indikator lingkungan per bangunan:")
print(buildings[["CF", "AOD", "LST", "NDVI", "NDBI", "LC_score"]].describe().round(3))

# ==========================================================
# 3.2  NORMALISASI & AGREGASI INDIKATOR
# ==========================================================

# Validasi terakhir: pastikan kolom mentah benar-benar ada di 'buildings'
# sebelum dinormalisasi, supaya error (jika ada) muncul di sini dengan
# pesan jelas, bukan nyasar jadi KeyError di tahap visualisasi nanti.
required_raw_cols = ["CF", "AOD", "LST", "NDVI", "NDBI", "LC_score"]
missing_raw = [c for c in required_raw_cols if c not in buildings.columns]
if missing_raw:
    raise KeyError(
        f"Kolom mentah berikut tidak ditemukan di 'buildings': {missing_raw}. "
        f"Pastikan Cell B (ekstraksi) sudah dijalankan SETELAH Cell A "
        f"(definisi env_stack) pada sesi yang sama."
    )

def minmax(s):
    """Min-max scaling yang aman: jika semua nilai sama (min==max),
    kembalikan 0.5 di semua baris (netral) alih-alih NaN/0 yang
    menyesatkan, dan beri peringatan agar penyebabnya jelas terlihat."""
    rng = s.max() - s.min()
    if rng == 0 or pd.isna(rng):
        print(f"   ⚠️ Kolom '{s.name}' punya nilai konstan/kosong (min=max={s.min()}). "
              f"Diisi 0.5 (netral) untuk semua baris.")
        return pd.Series(0.5, index=s.index)
    return (s - s.min()) / rng

# --- Diagnostik cepat sebelum normalisasi ---
print("\n🔍 DIAGNOSTIK kolom mentah sebelum normalisasi:")
for c in required_raw_cols:
    n_nan = buildings[c].isna().sum()
    print(f"   {c}: min={buildings[c].min():.4f} | max={buildings[c].max():.4f} | "
          f"unique={buildings[c].nunique()} | NaN={n_nan}")

# --- Normalisasi tiap indikator ke 0-1 ---
# Arah normalisasi penting: semakin tinggi nilai -> semakin terdegradasi,
# KECUALI NDVI (vegetasi tinggi = kondisi lingkungan BAIK, jadi dibalik).

buildings["CF_n"]    = minmax(buildings["CF"])          # makin berawan -> dianggap netral-degradasi kecil
buildings["AOD_n"]   = minmax(buildings["AOD"])         # makin tinggi aerosol -> makin terdegradasi
buildings["LST_n"]   = minmax(buildings["LST"])         # makin panas -> makin terdegradasi (urban heat island)
buildings["NDVI_n"]  = 1 - minmax(buildings["NDVI"])    # makin hijau -> makin RENDAH degradasi (dibalik)
buildings["NDBI_n"]  = minmax(buildings["NDBI"])        # makin built-up -> makin terdegradasi
buildings["LC_n"]    = minmax(buildings["LC_score"])    # sudah dalam skala skor degradasi land cover

print("\n[3.1] Indikator lingkungan berhasil diekstrak & dinormalisasi sementara.")

# --- Agregasi berbobot menjadi Environmental Degradation Index ---
# Bobot dapat disesuaikan sesuai konteks studi/sensitivitas analysis.
ENV_WEIGHTS = {
    "AOD_n":  0.20,   # kualitas udara
    "LST_n":  0.25,   # suhu permukaan / urban heat island
    "NDVI_n": 0.20,   # vegetasi
    "NDBI_n": 0.15,   # built-up density
    "LC_n":   0.15,   # tutupan lahan
    "CF_n":   0.05,   # cloud fraction -> bobot kecil, lebih sebagai indikator pendukung
}
assert abs(sum(ENV_WEIGHTS.values()) - 1.0) < 1e-6, "Bobot ENV_WEIGHTS harus berjumlah 1!"

buildings["env_index_raw"] = sum(
    buildings[col] * w for col, w in ENV_WEIGHTS.items()
)

# Renormalisasi ke 0-1 (jaga-jaga agar rentang akhir tetap rapi)
buildings["env_index"] = minmax(buildings["env_index_raw"])

buildings["env_class"] = pd.cut(
    buildings["env_index"],
    bins=[-0.001, 0.333, 0.667, 1.001],
    labels=["Rendah", "Sedang", "Tinggi"],
)

print("\n[3.2] Environmental Degradation Index (0-1) -> selesai.")
print(buildings[["building_id", "env_index", "env_class"]].describe(include="all").round(3))
print(f"\nDistribusi klasifikasi (semakin tinggi = semakin terdegradasi):")
print(buildings["env_class"].value_counts())

# ==========================================================
# OUTPUT 3 — ENVIRONMENTAL DEGRADATION INDEX
# ==========================================================

output3_cols = [
    "building_id", "centroid_lon", "centroid_lat",
    "CF", "AOD", "LST", "NDVI", "NDBI", "LC_score",
    "CF_n", "AOD_n", "LST_n", "NDVI_n", "NDBI_n", "LC_n",
    "env_index_raw", "env_index", "env_class",
    "geometry",
]
output3_cols = [c for c in output3_cols if c in buildings.columns]
output3 = buildings[output3_cols]

output3.to_file("/content/drive/MyDrive/GISACT/output3_env_degradation_index.geojson", driver="GeoJSON")
output3.drop(columns="geometry").to_csv("/content/drive/MyDrive/GISACT/output3_env_degradation_index.csv", index=False)

print("\n✅ OUTPUT 3 tersimpan:")
print("   - /content/drive/MyDrive/GISACT/output3_env_degradation_index.geojson")
print("   - /content/drive/MyDrive/GISACT/output3_env_degradation_index.csv")

# ==========================================================
# CELL C — Visualisasi (matplotlib, tanpa GEE)
# ==========================================================

# Bersihkan figure-figure kosong yang mungkin tersisa dari run sebelumnya
# (geopandas.plot() dengan legend=True kadang membuat figure colorbar
# sementara di belakang layar -> muncul sebagai placeholder kosong di output)
plt.close("all")

fig, axes = plt.subplots(2, 3, figsize=(20, 12))

# --- Peta indikator individual ---
indicator_specs = [
    ("AOD_n",  "Aerosol Optical Depth (norm.)", "Reds"),
    ("LST_n",  "Land Surface Temperature (norm.)", "OrRd"),
    ("NDVI_n", "Degradasi Vegetasi (norm., terbalik)", "YlGn"),
    ("NDBI_n", "Built-up Index (norm.)", "Oranges"),
    ("LC_n",   "Skor Degradasi Land Cover (norm.)", "PuRd"),
]

# CATATAN: parameter disederhanakan (tanpa edgecolor/linewidth/legend_kwds)
# karena kombinasi tersebut terbukti menyebabkan savefig(bbox_inches="tight")
# salah menghitung bounding box pada 36000+ polygon kecil, menghasilkan PNG
# putih kosong. legend=True saja tanpa legend_kwds custom sudah cukup aman.
for ax, (col, title, cmap) in zip(axes.flat[:5], indicator_specs):
    output3.plot(column=col, cmap=cmap, legend=True, ax=ax)
    ax.set_title(title, fontsize=11)
    ax.set_xlabel("")
    ax.set_ylabel("")

# ==========================================================
# CELL C — Visualisasi (matplotlib, tanpa GEE)
# ==========================================================

# Bersihkan figure-figure kosong yang mungkin tersisa dari run sebelumnya
# (geopandas.plot() dengan legend=True kadang membuat figure colorbar
# sementara di belakang layar -> muncul sebagai placeholder kosong di output)
plt.close("all")

fig, axes = plt.subplots(2, 3, figsize=(20, 12))

# --- Semua 6 peta (5 indikator + 1 indeks final) dalam SATU loop konsisten ---
# Sebelumnya panel ke-6 ditangani terpisah di luar loop (ax = axes.flat[5]
# secara manual) dan entah kenapa gagal render meski datanya valid. Dengan
# menyatukan semuanya ke satu loop yang identik strukturnya, kita hilangkan
# kemungkinan perbedaan perlakuan antar axis yang menyebabkan masalah itu.
indicator_specs = [
    ("AOD_n",      "Aerosol Optical Depth (norm.)", "Reds"),
    ("LST_n",      "Land Surface Temperature (norm.)", "OrRd"),
    ("NDVI_n",     "Degradasi Vegetasi (norm., terbalik)", "YlGn"),
    ("NDBI_n",     "Built-up Index (norm.)", "Oranges"),
    ("LC_n",       "Skor Degradasi Land Cover (norm.)", "PuRd"),
    ("env_index",  "Environmental Degradation Index (Final)", "RdYlGn_r"),
]

for ax, (col, title, cmap) in zip(axes.flat, indicator_specs):
    output3.plot(column=col, cmap=cmap, legend=True, ax=ax)
    ax.set_title(title, fontsize=11)
    ax.set_xlabel("")
    ax.set_ylabel("")

plt.tight_layout()
plt.savefig("/content/drive/MyDrive/GISACT/output3_env_indicators_map.png", dpi=600)
plt.show()

plt.tight_layout()
plt.savefig("/content/drive/MyDrive/GISACT/output3_env_indicators_map.png", dpi=600)
plt.show()

print("✅ Peta indikator tersimpan: /content/drive/MyDrive/GISACT/output3_env_indicators_map.png")

# --- Peta klasifikasi terpisah ---
fig2, ax2 = plt.subplots(figsize=(9, 8))
class_colors = {"Rendah": "#639922", "Sedang": "#EF9F27", "Tinggi": "#A32D2D"}
output3["color"] = output3["env_class"].map(class_colors)
output3.plot(color=output3["color"], linewidth=0.3, edgecolor="black", ax=ax2)
ax2.set_title("Klasifikasi Environmental Degradation Index")
legend_elements = [Patch(facecolor=color, edgecolor="black", label=label)
                    for label, color in class_colors.items()]
ax2.legend(handles=legend_elements, loc="upper right", title="Tingkat Degradasi")
plt.tight_layout()
plt.savefig("/content/drive/MyDrive/GISACT/output3_env_class_map.png", dpi=150, bbox_inches="tight")
plt.show()

print("✅ Peta klasifikasi tersimpan: /content/drive/MyDrive/GISACT/output3_env_class_map.png")

# --- Korelasi antar indikator (heatmap sederhana) ---
fig3, ax3 = plt.subplots(figsize=(7, 6))
corr_cols = ["CF_n", "AOD_n", "LST_n", "NDVI_n", "NDBI_n", "LC_n", "env_index"]
corr_matrix = buildings[corr_cols].corr()
im = ax3.imshow(corr_matrix, cmap="RdBu_r", vmin=-1, vmax=1)
ax3.set_xticks(range(len(corr_cols)))
ax3.set_yticks(range(len(corr_cols)))
ax3.set_xticklabels(corr_cols, rotation=45, ha="right")
ax3.set_yticklabels(corr_cols)
for i in range(len(corr_cols)):
    for j in range(len(corr_cols)):
        ax3.text(j, i, f"{corr_matrix.iloc[i, j]:.2f}", ha="center", va="center",
                  color="white" if abs(corr_matrix.iloc[i, j]) > 0.5 else "black", fontsize=9)
plt.colorbar(im, ax=ax3, shrink=0.8, label="Korelasi")
ax3.set_title("Korelasi Antar Indikator Lingkungan")
plt.tight_layout()
plt.savefig("/content/drive/MyDrive/GISACT/utput3_correlation_heatmap.png", dpi=150, bbox_inches="tight")
plt.show()

print("✅ Heatmap korelasi tersimpan: /content/drive/MyDrive/GISACT/output3_correlation_heatmap.png")

"""**"PENGHITUNGAN POTENSI SOLAR PV"**"""

# ==========================================================
# TASK 4 — INTEGRASI MULTI-KRITERIA UNTUK PENENTUAN PRIORITAS
# (sambungan dari Task 1, 2, 3 - variabel 'buildings' sudah tersedia)
# ==========================================================
# Prasyarat dari Task 1-3 yang sudah ada di memori 'buildings':
#   - pv_index     (Output 1 - Solar PV Potential Index, 0-1)
#   - econ_index   (Output 2 - Economic Value Index, 0-1)
#   - env_index    (Output 3 - Environmental Degradation Index, 0-1)
#
# Interpretasi: SEMUA tiga indeks searah dengan prioritas -> semakin
# tinggi nilainya, semakin tinggi prioritas pemasangan Solar PV.
# ==========================================================
# 4.1  PENGGABUNGAN KETIGA INDEKS
# ==========================================================

# --- Validasi: pastikan ketiga indeks ada & dalam rentang 0-1 ---
required_indices = ["pv_index", "econ_index", "env_index"]
missing = [c for c in required_indices if c not in buildings.columns]
if missing:
    raise KeyError(
        f"Kolom indeks berikut tidak ditemukan di 'buildings': {missing}. "
        f"Pastikan Task 1, 2, dan 3 sudah dijalankan lengkap sebelum Task 4."
    )

print("🔍 Validasi rentang nilai ketiga indeks:")
for col in required_indices:
    mn, mx = buildings[col].min(), buildings[col].max()
    n_nan = buildings[col].isna().sum()
    status = "✅ OK" if (0 <= mn and mx <= 1 and n_nan == 0) else "⚠️ PERIKSA"
    print(f"   {col}: min={mn:.3f} | max={mx:.3f} | NaN={n_nan} | {status}")

# Jaga-jaga: isi NaN dengan median jika ada (seharusnya sudah bersih dari Task 1-3)
for col in required_indices:
    if buildings[col].isna().sum() > 0:
        buildings[col] = buildings[col].fillna(buildings[col].median())
        print(f"   ⚠️ NaN di '{col}' diisi dengan median.")

print("\n[4.1] Ketiga indeks (O1, O2, O3) siap diintegrasikan.")
print(buildings[required_indices].describe().round(3))

# ==========================================================
# 4.2  PENENTUAN SKOR PRIORITAS (WLC) + UJI SENSITIVITAS
# ==========================================================

def minmax(s):
    rng = s.max() - s.min()
    if rng == 0 or pd.isna(rng):
        return pd.Series(0.5, index=s.index)
    return (s - s.min()) / rng


def compute_priority(gdf, w1, w2, w3, label="priority"):
    """
    Weighted Linear Combination (WLC):
    S = w1 * PV + w2 * Economics + w3 * Environment
    dengan w1, w2, w3 >= 0 dan w1+w2+w3 = 1
    """
    assert w1 >= 0 and w2 >= 0 and w3 >= 0, "Bobot tidak boleh negatif."
    total = w1 + w2 + w3
    assert abs(total - 1.0) < 1e-6, f"Bobot harus berjumlah 1, saat ini {total}"

    score = w1 * gdf["pv_index"] + w2 * gdf["econ_index"] + w3 * gdf["env_index"]
    return score

# -----------------------------------------------------
# Skenario bobot UTAMA (default)
# -----------------------------------------------------
W_MAIN = {"w1_pv": 0.40, "w2_econ": 0.35, "w3_env": 0.25}
assert abs(sum(W_MAIN.values()) - 1.0) < 1e-6, "Bobot utama harus berjumlah 1!"

buildings["priority_score"] = compute_priority(
    buildings, W_MAIN["w1_pv"], W_MAIN["w2_econ"], W_MAIN["w3_env"]
)

# Ranking (1 = prioritas tertinggi)
buildings["rank"] = buildings["priority_score"].rank(ascending=False, method="min").astype(int)

# Klasifikasi prioritas — pakai kuantil (33%/33%/33%) agar proporsional,
# berkaca dari pengalaman Task 3 di mana breakpoint tetap bisa sangat timpang.
buildings["priority_class"] = pd.qcut(
    buildings["priority_score"],
    q=3,
    labels=["Rendah", "Sedang", "Tinggi"],
    duplicates="drop",
)

# Klasifikasi alternatif breakpoint tetap (sebagai pembanding)
buildings["priority_class_fixed"] = pd.cut(
    buildings["priority_score"],
    bins=[-0.001, 0.333, 0.667, 1.001],
    labels=["Rendah", "Sedang", "Tinggi"],
)

print(f"\n[4.2] Priority Score (bobot utama: PV={W_MAIN['w1_pv']}, "
      f"Econ={W_MAIN['w2_econ']}, Env={W_MAIN['w3_env']}) -> selesai.")
print(buildings[["priority_score", "rank"]].describe().round(3))

print("\nDistribusi klasifikasi (kuantil, proporsional):")
print(buildings["priority_class"].value_counts())
print("\nDistribusi klasifikasi (breakpoint tetap, pembanding):")
print(buildings["priority_class_fixed"].value_counts())

# -----------------------------------------------------
# Uji Sensitivitas Pembobotan — beberapa skenario
# -----------------------------------------------------
SCENARIOS = {
    "Utama (PV 40% / Econ 35% / Env 25%)": (0.40, 0.35, 0.25),
    "Prioritas PV (PV 60%)":                (0.60, 0.25, 0.15),
    "Prioritas Ekonomi (Econ 60%)":         (0.25, 0.60, 0.15),
    "Prioritas Lingkungan (Env 60%)":       (0.25, 0.15, 0.60),
    "Seimbang (33/33/33)":                  (0.34, 0.33, 0.33),
}

print("\n🔬 UJI SENSITIVITAS PEMBOBOTAN:")
scenario_results = {}
for name, (w1, w2, w3) in SCENARIOS.items():
    score = compute_priority(buildings, w1, w2, w3)
    rank = score.rank(ascending=False, method="min").astype(int)
    scenario_results[name] = {"score": score, "rank": rank}
    buildings[f"score_{name}"] = score
    buildings[f"rank_{name}"] = rank

# Bandingkan ranking Top-20 antar skenario
top_n = 20
top20_main = buildings.nsmallest(top_n, "rank")["building_id"].values

sens_table = pd.DataFrame({"building_id": top20_main})
for name in SCENARIOS:
    rank_col = f"rank_{name}"
    sens_table[name] = buildings.set_index("building_id").loc[top20_main, rank_col].values

print(f"\nPerbandingan ranking Top-{top_n} bangunan (skenario utama) di seluruh skenario:")
print(sens_table.set_index("building_id").to_string())

# --- Stabilitas Top-20: berapa kali tiap bangunan top tetap masuk Top-20
#     di skenario lain ---
in_top_count = (sens_table.drop(columns="building_id") <= top_n).sum(axis=1)
sens_table["stability_count"] = in_top_count
sens_table["stability_pct"] = (in_top_count / len(SCENARIOS) * 100).round(1)

print(f"\nStabilitas Top-{top_n} (berapa % skenario building tsb tetap masuk Top-{top_n}):")
print(sens_table[["building_id", "stability_pct"]].sort_values("stability_pct", ascending=False).to_string(index=False))

# ==========================================================
# OUTPUT 4 — PRIORITY SCORE & BUILDING RANKING
# ==========================================================

output4_cols = [
    "building_id", "centroid_lon", "centroid_lat",
    "pv_index", "econ_index", "env_index",
    "priority_score", "rank", "priority_class", "priority_class_fixed",
    "geometry",
]
output4_cols = [c for c in output4_cols if c in buildings.columns]
output4 = buildings[output4_cols].sort_values("rank")

output4.to_file("/content/drive/MyDrive/GISACT/output4_priority_score.geojson", driver="GeoJSON")
output4.drop(columns="geometry").to_csv("/content/drive/MyDrive/GISACT/output4_priority_ranking.csv", index=False)

sens_table.to_csv("/content/drive/MyDrive/GISACT/output4_sensitivity_analysis.csv", index=False)

print("\n✅ OUTPUT 4 tersimpan:")
print("   - /content/drive/MyDrive/GISACT/output4_priority_score.geojson")
print("   - /content/drive/MyDrive/GISACT/output4_priority_ranking.csv")
print("   - /content/drive/MyDrive/GISACT/output4_sensitivity_analysis.csv")

print(f"\n🏆 TOP 20 BANGUNAN PRIORITAS SOLAR PV (skenario utama):")
print(output4.head(20)[["building_id", "pv_index", "econ_index", "env_index",
                          "priority_score", "rank", "priority_class"]].to_string(index=False))

# ==========================================================
# VISUALISASI
# ==========================================================

# -----------------------------------------------------
# Peta 1: Priority Score & Klasifikasi
# -----------------------------------------------------
plt.close("all")
fig, axes = plt.subplots(1, 2, figsize=(18, 8))

ax = axes[0]
output4.plot(column="priority_score", cmap="plasma", legend=True, ax=ax)
top20_gdf = output4.nsmallest(top_n, "rank")
top20_gdf.boundary.plot(ax=ax, color="cyan", linewidth=1.0)
ax.set_title(f"Priority Score (Cyan outline = Top {top_n})", fontsize=12)
ax.set_xlabel("")
ax.set_ylabel("")

ax2 = axes[1]
class_colors = {"Rendah": "#378ADD", "Sedang": "#EF9F27", "Tinggi": "#D85A30"}
output4["color"] = output4["priority_class"].map(class_colors)
output4.plot(color=output4["color"], ax=ax2)
ax2.set_title("Klasifikasi Prioritas (kuantil)", fontsize=12)
ax2.set_xlabel("")
ax2.set_ylabel("")
legend_elements = [Patch(facecolor=color, label=label) for label, color in class_colors.items()]
ax2.legend(handles=legend_elements, loc="upper right", title="Prioritas")

plt.tight_layout()
plt.savefig("/content/drive/MyDrive/GISACT/output4_priority_map.png", dpi=150)
plt.show()
print("✅ Peta prioritas tersimpan: /content/drive/MyDrive/GISACT/output4_priority_map.png")

# -----------------------------------------------------
# Grafik 2: Bar chart Top-20 + Distribusi kelas
# -----------------------------------------------------
plt.close("all")
fig2, axes2 = plt.subplots(1, 2, figsize=(18, 7))

ax = axes2[0]
top20_sorted = output4.nsmallest(top_n, "rank").sort_values("priority_score", ascending=True)
bar_colors = [class_colors.get(c, "gray") for c in top20_sorted["priority_class"]]
ax.barh(top20_sorted["building_id"].astype(str), top20_sorted["priority_score"], color=bar_colors)
ax.set_xlabel("Priority Score")
ax.set_title(f"Top {top_n} Bangunan Prioritas Tertinggi")
ax.grid(axis="x", alpha=0.3)

ax2 = axes2[1]
class_counts = buildings["priority_class"].value_counts().reindex(["Rendah", "Sedang", "Tinggi"])
bars = ax2.bar(class_counts.index, class_counts.values,
                color=[class_colors.get(c, "gray") for c in class_counts.index])
for bar, val in zip(bars, class_counts.values):
    ax2.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 5,
              str(val), ha="center", va="bottom", fontsize=11)
ax2.set_title("Distribusi Kelas Prioritas")
ax2.set_ylabel("Jumlah Bangunan")

plt.tight_layout()
plt.savefig("/content/drive/MyDrive/GISACT/output4_top20_distribution.png", dpi=150)
plt.show()
print("✅ Grafik Top-20 & distribusi tersimpan: /content/drive/MyDrive/GISACT/output4_top20_distribution.png")

# -----------------------------------------------------
# Grafik 3: Sensitivitas — perbandingan skor antar skenario (line plot)
# -----------------------------------------------------
plt.close("all")
fig3, ax3 = plt.subplots(figsize=(11, 6))

# Ambil 5 bangunan teratas dari skenario utama, lihat skornya di tiap skenario
top5_ids = buildings.nsmallest(5, "rank")["building_id"].values
x_pos = np.arange(len(SCENARIOS))

for bid in top5_ids:
    row = buildings[buildings["building_id"] == bid].iloc[0]
    scores = [row[f"score_{name}"] for name in SCENARIOS]
    ax3.plot(x_pos, scores, marker="o", label=f"Bangunan #{bid}")

ax3.set_xticks(x_pos)
ax3.set_xticklabels(list(SCENARIOS.keys()), rotation=20, ha="right", fontsize=9)
ax3.set_ylabel("Priority Score")
ax3.set_title("Sensitivitas Priority Score Top-5 Bangunan Terhadap Skenario Bobot")
ax3.legend(loc="best", fontsize=9)
ax3.grid(alpha=0.3)

plt.tight_layout()
plt.savefig("/content/drive/MyDrive/GISACT/output4_sensitivity_lineplot.png", dpi=150)
plt.show()
print("✅ Grafik sensitivitas tersimpan: /content/drive/MyDrive/GISACT/output4_sensitivity_lineplot.png")

# -----------------------------------------------------
# Grafik 4: Scatter PV vs Economic, warna = Env, ukuran = Priority Score
# -----------------------------------------------------
plt.close("all")
fig4, ax4 = plt.subplots(figsize=(9, 8))
scatter = ax4.scatter(
    buildings["pv_index"], buildings["econ_index"],
    c=buildings["env_index"], cmap="RdYlGn_r",
    s=buildings["priority_score"] * 100 + 10,
    alpha=0.5, edgecolor="none",
)
plt.colorbar(scatter, ax=ax4, label="Environmental Degradation Index")
ax4.set_xlabel("Solar PV Potential Index")
ax4.set_ylabel("Economic Value Index")
ax4.set_title("Hubungan Ketiga Indeks per Bangunan\n(ukuran titik = Priority Score)")
ax4.grid(alpha=0.2)

plt.tight_layout()
plt.savefig("/content/drive/MyDrive/GISACT/output4_scatter_3index.png", dpi=150)
plt.show()
print("✅ Scatter plot 3 indeks tersimpan: /content/drive/MyDrive/GISACT/output4_scatter_3index.png")

print("\n🎉 TASK 4 SELESAI. Output 4 siap dipakai untuk tahap Validasi & Uji Ketidakpastian (bagian 5).")

"""**VALIDASI**"""

# ==========================================================
# TASK 5 — VALIDASI MODEL, SENSITIVITAS LANJUTAN, ROBUSTNESS,
#          & IDENTIFIKASI SUMBER KETIDAKPASTIAN
# (sambungan dari Task 1-4 - variabel 'buildings', 'model',
#  'X', 'X_cols', 'y', 'scaler', 'SCENARIOS', 'W_MAIN' sudah tersedia)
# ==========================================================

import numpy as np
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
from matplotlib.patches import Patch
from scipy import stats
from scipy.stats import spearmanr, kendalltau
from sklearn.model_selection import KFold, cross_val_score
from shapely.validation import explain_validity

OUT_DIR = "/content/drive/MyDrive/GISACT"
np.random.seed(42)

print("\n" + "=" * 70)
print("🧪 TASK 5 — VALIDASI, SENSITIVITAS LANJUTAN, ROBUSTNESS, KETIDAKPASTIAN")
print("=" * 70)

# ==========================================================
# 5.1  VALIDASI DATA & MODEL
#      (a) Kualitas input data   (b) Konsistensi spasial
# ==========================================================
print("\n[5.1] VALIDASI DATA & MODEL")
print("-" * 70)

validation_report = []

def _log_check(name, status, detail):
    validation_report.append({"check": name, "status": status, "detail": detail})
    icon = "✅" if status == "OK" else ("⚠️" if status == "WARNING" else "❌")
    print(f"   {icon} {name}: {detail}")

# --- (a.1) Kelengkapan data: missing value pada kolom kunci ---
key_cols = [
    "building_id", "geometry", "height", "roof_area_m2",
    "pv_index", "econ_index", "env_index", "priority_score", "rank",
]
key_cols = [c for c in key_cols if c in buildings.columns]
for col in key_cols:
    n_na = buildings[col].isna().sum()
    pct = 100 * n_na / len(buildings)
    status = "OK" if n_na == 0 else ("WARNING" if pct < 5 else "FAIL")
    _log_check(f"Missing value: {col}", status, f"{n_na} baris kosong ({pct:.2f}%)")

# --- (a.2) building_id unik (tidak ada duplikasi record) ---
n_dup_id = buildings["building_id"].duplicated().sum()
_log_check(
    "Duplikasi building_id", "OK" if n_dup_id == 0 else "FAIL",
    f"{n_dup_id} ID duplikat ditemukan",
)

# --- (a.3) Rentang nilai indeks & skor harus valid (0-1) ---
for col in ["pv_index", "econ_index", "env_index", "priority_score"]:
    if col not in buildings.columns:
        continue
    mn, mx = buildings[col].min(), buildings[col].max()
    out_of_range = ((buildings[col] < -1e-6) | (buildings[col] > 1 + 1e-6)).sum()
    status = "OK" if out_of_range == 0 else "WARNING"
    _log_check(
        f"Rentang nilai: {col}", status,
        f"min={mn:.3f}, max={mx:.3f}, {out_of_range} nilai di luar [0,1]",
    )

# --- (a.4) Deteksi outlier ekstrem pada atribut fisik (IQR method) ---
for col in ["roof_area_m2", "height"]:
    if col not in buildings.columns:
        continue
    q1, q3 = buildings[col].quantile([0.25, 0.75])
    iqr = q3 - q1
    lo, hi = q1 - 3 * iqr, q3 + 3 * iqr
    n_out = ((buildings[col] < lo) | (buildings[col] > hi)).sum()
    pct = 100 * n_out / len(buildings)
    status = "OK" if pct < 1 else ("WARNING" if pct < 5 else "FAIL")
    _log_check(
        f"Outlier ekstrem: {col}", status,
        f"{n_out} bangunan ({pct:.2f}%) di luar rentang wajar [{lo:.1f}, {hi:.1f}]",
    )

# --- (a.5) Proporsi bangunan yang memakai nilai tinggi default (10 m) ---
if "height" in buildings.columns:
    n_default_h = (np.isclose(buildings["height"], 10.0)).sum()
    pct_default = 100 * n_default_h / len(buildings)
    status = "OK" if pct_default < 20 else ("WARNING" if pct_default < 50 else "FAIL")
    _log_check(
        "Ketergantungan nilai default (height=10m)", status,
        f"{n_default_h} bangunan ({pct_default:.1f}%) memakai nilai default, "
        f"bukan hasil observasi/sumber data asli",
    )

# --- (b.1) Validitas geometri (topologi) ---
invalid_geom = ~buildings.geometry.is_valid
n_invalid = invalid_geom.sum()
status = "OK" if n_invalid == 0 else "WARNING"
_log_check("Validitas geometri", status, f"{n_invalid} geometri tidak valid (self-intersect/dll)")
if n_invalid > 0:
    sample_reason = explain_validity(buildings.loc[invalid_geom, "geometry"].iloc[0])
    print(f"      contoh alasan: {sample_reason}")

# --- (b.2) Geometri kosong / null ---
n_empty = buildings.geometry.is_empty.sum()
_log_check("Geometri kosong", "OK" if n_empty == 0 else "FAIL", f"{n_empty} geometri kosong")

# --- (b.3) Konsistensi CRS ---
_log_check(
    "Konsistensi CRS", "OK" if buildings.crs is not None else "FAIL",
    f"CRS aktif: {buildings.crs}",
)

# --- (b.4) Konsistensi spasial: seluruh bangunan berada di dalam AOI ---
try:
    roi_geom_local = gpd.GeoDataFrame.from_features(
        json.loads(json.dumps(roi.getInfo()))["features"]
    ).set_crs("EPSG:4326").unary_union
    within_roi = buildings.geometry.centroid.within(roi_geom_local.buffer(0.001))
    n_outside = (~within_roi).sum()
    pct_outside = 100 * n_outside / len(buildings)
    status = "OK" if pct_outside < 1 else ("WARNING" if pct_outside < 5 else "FAIL")
    _log_check(
        "Konsistensi spasial (bangunan vs AOI)", status,
        f"{n_outside} bangunan ({pct_outside:.2f}%) berada di luar batas AOI",
    )
except Exception as e:
    _log_check("Konsistensi spasial (bangunan vs AOI)", "WARNING", f"tidak dapat diverifikasi ({e})")

# --- (b.5) Duplikasi geometri (kemungkinan bangunan tercatat ganda) ---
n_dup_geom = buildings.geometry.apply(lambda g: g.wkb).duplicated().sum()
_log_check(
    "Duplikasi geometri", "OK" if n_dup_geom == 0 else "WARNING",
    f"{n_dup_geom} geometri identik terdeteksi",
)

# --- (b.6) Autokorelasi spasial sederhana (Moran's I) pada priority_score ---
# Digunakan untuk memastikan skor prioritas punya pola spasial yang masuk akal
# (bukan noise acak murni), sebagai bagian dari uji konsistensi spasial.
try:
    from libpysal.weights import Queen
    from esda.moran import Moran

    w = Queen.from_dataframe(buildings, use_index=False, silence_warnings=True)
    w.transform = "r"
    moran = Moran(buildings["priority_score"].values, w)
    status = "OK" if moran.p_sim < 0.05 else "WARNING"
    _log_check(
        "Autokorelasi spasial (Moran's I) priority_score", status,
        f"I={moran.I:.3f}, p={moran.p_sim:.3f} "
        f"({'terpola secara spasial' if moran.p_sim < 0.05 else 'tidak signifikan / mendekati acak'})",
    )
except ImportError:
    _log_check(
        "Autokorelasi spasial (Moran's I)", "WARNING",
        "library 'libpysal'/'esda' belum terinstall -> lewati "
        "(opsional: !pip install -q libpysal esda untuk mengaktifkan)",
    )
except Exception as e:
    _log_check("Autokorelasi spasial (Moran's I)", "WARNING", f"gagal dihitung ({e})")

validation_df = pd.DataFrame(validation_report)
n_fail = (validation_df["status"] == "FAIL").sum()
n_warn = (validation_df["status"] == "WARNING").sum()
print(f"\n[5.1] Ringkasan validasi: {len(validation_df) - n_fail - n_warn} OK, "
      f"{n_warn} WARNING, {n_fail} FAIL (dari {len(validation_df)} pemeriksaan).")

validation_df.to_csv(f"{OUT_DIR}/output5_data_validation_report.csv", index=False)
print(f"✅ Laporan validasi tersimpan: {OUT_DIR}/output5_data_validation_report.csv")

# ==========================================================
# 5.2  ANALISIS SENSITIVITAS LANJUTAN
#      (variasi bobot secara sistematis, perubahan ranking,
#       identifikasi bangunan prioritas stabil)
# ==========================================================
print("\n[5.2] ANALISIS SENSITIVITAS LANJUTAN")
print("-" * 70)

N_WEIGHT_SAMPLES = 1000
TOP_N = 20

# --- Sampling bobot acak dari distribusi Dirichlet (w1+w2+w3=1, w>=0) ---
# alpha=(4,4,4) -> bobot condong di sekitar area seimbang, tapi tetap
# memberi variasi luas mendekati kombinasi bobot ekstrem.
alpha = np.array([4.0, 4.0, 4.0])
weight_samples = np.random.dirichlet(alpha, size=N_WEIGHT_SAMPLES)

score_matrix = np.zeros((len(buildings), N_WEIGHT_SAMPLES))
rank_matrix = np.zeros((len(buildings), N_WEIGHT_SAMPLES), dtype=int)

pv = buildings["pv_index"].values
econ = buildings["econ_index"].values
env = buildings["env_index"].values

for i, (w1, w2, w3) in enumerate(weight_samples):
    s = w1 * pv + w2 * econ + w3 * env
    score_matrix[:, i] = s
    rank_matrix[:, i] = pd.Series(s).rank(ascending=False, method="min").astype(int).values

# --- Ranking utama sebagai acuan ---
main_rank = buildings["rank"].values

# --- Korelasi ranking (Spearman & Kendall) antara skenario UTAMA vs tiap sampel bobot ---
spearman_vals = [spearmanr(main_rank, rank_matrix[:, i]).correlation for i in range(N_WEIGHT_SAMPLES)]
kendall_vals = [kendalltau(main_rank, rank_matrix[:, i]).correlation for i in range(N_WEIGHT_SAMPLES)]

print(f"Simulasi {N_WEIGHT_SAMPLES} kombinasi bobot acak (Dirichlet) vs skenario utama:")
print(f"   Korelasi Spearman rata-rata : {np.mean(spearman_vals):.3f} "
      f"(min={np.min(spearman_vals):.3f}, max={np.max(spearman_vals):.3f})")
print(f"   Korelasi Kendall-tau rata-rata: {np.mean(kendall_vals):.3f} "
      f"(min={np.min(kendall_vals):.3f}, max={np.max(kendall_vals):.3f})")

# --- Perubahan ranking (delta rank) tiap bangunan akibat variasi bobot ---
rank_delta = rank_matrix - main_rank.reshape(-1, 1)
buildings["rank_delta_mean"] = np.mean(np.abs(rank_delta), axis=1)
buildings["rank_delta_std"] = np.std(rank_matrix, axis=1)

print("\nStatistik perubahan ranking (|delta rank| terhadap skenario utama), seluruh bangunan:")
print(buildings["rank_delta_mean"].describe().round(2))

# --- Identifikasi BANGUNAN PRIORITAS STABIL ---
# "Stabil" = tetap masuk Top-N di proporsi besar sampel bobot acak.
in_topN = (rank_matrix <= TOP_N)
buildings["topN_inclusion_prob"] = in_topN.mean(axis=1)  # 0-1

STABLE_THRESHOLD = 0.80  # >=80% sampel bobot -> dianggap stabil
buildings["priority_stable"] = buildings["topN_inclusion_prob"] >= STABLE_THRESHOLD

stable_buildings = buildings.loc[
    buildings["priority_stable"], ["building_id", "rank", "priority_score", "topN_inclusion_prob"]
].sort_values("topN_inclusion_prob", ascending=False)

n_stable = len(stable_buildings)
print(f"\n🏆 Bangunan PRIORITAS STABIL (masuk Top-{TOP_N} pada >= {STABLE_THRESHOLD*100:.0f}% "
      f"dari {N_WEIGHT_SAMPLES} kombinasi bobot acak): {n_stable} bangunan")
print(stable_buildings.head(20).to_string(index=False))

# --- Bandingkan juga dengan 5 skenario diskrit (Task 4) bila tersedia ---
if "SCENARIOS" in globals():
    scenario_rank_cols = [f"rank_{name}" for name in SCENARIOS if f"rank_{name}" in buildings.columns]
    if scenario_rank_cols:
        corr_matrix = buildings[["rank"] + scenario_rank_cols].corr(method="spearman")
        print("\nMatriks korelasi Spearman antar-ranking skenario diskrit (Task 4):")
        print(corr_matrix.round(3).to_string())

# ==========================================================
# GRAFIK 5.2a — Distribusi korelasi Spearman & heatmap Top-N inclusion
# ==========================================================
plt.close("all")
fig5a, axes5a = plt.subplots(1, 2, figsize=(16, 6))

ax = axes5a[0]
ax.hist(spearman_vals, bins=30, color="#378ADD", edgecolor="black", alpha=0.8)
ax.axvline(np.mean(spearman_vals), color="#D85A30", linestyle="--",
           label=f"Rata-rata = {np.mean(spearman_vals):.3f}")
ax.set_xlabel("Korelasi Spearman (vs skenario utama)")
ax.set_ylabel("Frekuensi")
ax.set_title(f"Stabilitas Ranking terhadap {N_WEIGHT_SAMPLES} Variasi Bobot Acak")
ax.legend()
ax.grid(alpha=0.2)

ax2 = axes5a[1]
top_stable_plot = buildings.nlargest(20, "topN_inclusion_prob").sort_values("topN_inclusion_prob")
bar_colors2 = ["#1D9E75" if v >= STABLE_THRESHOLD else "#EF9F27" for v in top_stable_plot["topN_inclusion_prob"]]
ax2.barh(top_stable_plot["building_id"].astype(str), top_stable_plot["topN_inclusion_prob"], color=bar_colors2)
ax2.axvline(STABLE_THRESHOLD, color="#D85A30", linestyle="--", label=f"Ambang stabil ({STABLE_THRESHOLD:.0%})")
ax2.set_xlabel(f"Probabilitas masuk Top-{TOP_N}")
ax2.set_title("Bangunan dengan Probabilitas Prioritas Tertinggi")
ax2.legend()
ax2.grid(axis="x", alpha=0.2)

plt.tight_layout()
plt.savefig(f"{OUT_DIR}/output5_sensitivity_advanced.png", dpi=150)
plt.show()
print(f"✅ Grafik sensitivitas lanjutan tersimpan: {OUT_DIR}/output5_sensitivity_advanced.png")

# ==========================================================
# 5.3  UJI ROBUSTNESS
#      (a) Monte Carlo ketidakpastian input
#      (b) Bootstrap ranking
#      (c) Out-of-sample test (model prediktif Task 2)
# ==========================================================
print("\n[5.3] UJI ROBUSTNESS")
print("-" * 70)

# -----------------------------------------------------
# (a) Monte Carlo — ketidakpastian NILAI INPUT (bukan hanya bobot)
# -----------------------------------------------------
# Mensimulasikan ketidakpastian pengukuran/derivasi indeks (misal akibat
# resolusi raster GHI/DNI/GTI ~250m, rata-rata cloud fraction 1 tahun,
# proxy ekonomi, dll) dengan menambahkan noise Gaussian kecil pada
# ketiga indeks, DIKOMBINASIKAN dengan bobot acak dari 5.2.
N_MC = 1000
NOISE_STD = 0.05  # asumsi ketidakpastian ~5% dari skala indeks (0-1)

mc_score_matrix = np.zeros((len(buildings), N_MC))
mc_rank_matrix = np.zeros((len(buildings), N_MC), dtype=int)
mc_weights = np.random.dirichlet(alpha, size=N_MC)

for i in range(N_MC):
    pv_noisy = np.clip(pv + np.random.normal(0, NOISE_STD, size=len(pv)), 0, 1)
    econ_noisy = np.clip(econ + np.random.normal(0, NOISE_STD, size=len(econ)), 0, 1)
    env_noisy = np.clip(env + np.random.normal(0, NOISE_STD, size=len(env)), 0, 1)
    w1, w2, w3 = mc_weights[i]
    s = w1 * pv_noisy + w2 * econ_noisy + w3 * env_noisy
    mc_score_matrix[:, i] = s
    mc_rank_matrix[:, i] = pd.Series(s).rank(ascending=False, method="min").astype(int).values

buildings["mc_score_mean"] = mc_score_matrix.mean(axis=1)
buildings["mc_score_ci_low"] = np.percentile(mc_score_matrix, 5, axis=1)
buildings["mc_score_ci_high"] = np.percentile(mc_score_matrix, 95, axis=1)
buildings["mc_rank_mean"] = mc_rank_matrix.mean(axis=1)
buildings["mc_rank_std"] = mc_rank_matrix.std(axis=1)
buildings["mc_topN_prob"] = (mc_rank_matrix <= TOP_N).mean(axis=1)

print(f"Monte Carlo ({N_MC} iterasi, noise input ±{NOISE_STD:.0%}, bobot acak):")
print(f"   Rata-rata lebar CI 90% priority_score: "
      f"{(buildings['mc_score_ci_high'] - buildings['mc_score_ci_low']).mean():.3f}")
print(f"   Rata-rata std ranking antar-iterasi   : {buildings['mc_rank_std'].mean():.1f} posisi")
print(f"   Jumlah bangunan Top-{TOP_N} dgn probabilitas >= {STABLE_THRESHOLD:.0%} tetap masuk Top-{TOP_N}: "
      f"{(buildings['mc_topN_prob'] >= STABLE_THRESHOLD).sum()}")

# -----------------------------------------------------
# (b) Bootstrap — resampling bangunan untuk uji stabilitas komposisi Top-N
# -----------------------------------------------------
# Bootstrap dilakukan pada POPULASI bangunan (resample with replacement)
# untuk melihat seberapa stabil KOMPOSISI Top-N bila dataset sedikit
# berbeda (mensimulasikan variasi sampling/pencatatan data bangunan).
N_BOOT = 500
boot_top_ids_count = pd.Series(0, index=buildings["building_id"])
main_top_ids = set(buildings.nsmallest(TOP_N, "rank")["building_id"])

jaccard_scores = []
for b in range(N_BOOT):
    boot_idx = np.random.choice(len(buildings), size=len(buildings), replace=True)
    boot_sample = buildings.iloc[boot_idx]
    boot_score = compute_priority(boot_sample, W_MAIN["w1_pv"], W_MAIN["w2_econ"], W_MAIN["w3_env"])
    boot_rank = boot_score.rank(ascending=False, method="min")
    boot_top_ids = set(boot_sample.loc[boot_rank <= TOP_N, "building_id"])
    boot_top_ids_count.loc[list(boot_top_ids & set(boot_top_ids_count.index))] += 1
    inter = len(boot_top_ids & main_top_ids)
    union = len(boot_top_ids | main_top_ids)
    jaccard_scores.append(inter / union if union > 0 else np.nan)

buildings["bootstrap_topN_freq"] = (boot_top_ids_count / N_BOOT).reindex(buildings["building_id"]).values
mean_jaccard = np.nanmean(jaccard_scores)

print(f"\nBootstrap ({N_BOOT} resample, with replacement):")
print(f"   Rata-rata indeks Jaccard komposisi Top-{TOP_N} (vs data asli): {mean_jaccard:.3f} "
      f"(1.0 = identik sempurna)")
print(f"   Interpretasi: {'komposisi Top-N cukup stabil' if mean_jaccard >= 0.6 else 'komposisi Top-N cukup sensitif terhadap variasi sampel data'}")

# -----------------------------------------------------
# (c) Out-of-sample test — model prediktif (Random Forest, Task 2.2)
# -----------------------------------------------------
# Model 'model' (RandomForestRegressor) dari Task 2.2 bersifat prediktif
# (economic_proxy). Di Task 2 hanya diuji dengan satu train/test split;
# di sini digunakan K-Fold Cross Validation untuk uji generalisasi
# (out-of-sample) yang lebih robust terhadap pembagian data yang "beruntung".
if "model" in globals() and "X" in globals() and "y" in globals():
    kf = KFold(n_splits=5, shuffle=True, random_state=42)
    X_arr = scaler.transform(X) if "scaler" in globals() else X.values

    cv_r2 = cross_val_score(model, X_arr, y, cv=kf, scoring="r2")
    cv_mae = -cross_val_score(model, X_arr, y, cv=kf, scoring="neg_mean_absolute_error")

    print(f"\nOut-of-sample test (5-Fold Cross Validation) — model Economic Value (Task 2.2):")
    print(f"   R2 per fold : {np.round(cv_r2, 3)}")
    print(f"   MAE per fold: {np.round(cv_mae, 2)}")
    print(f"   R2  rata-rata: {cv_r2.mean():.3f} ± {cv_r2.std():.3f}")
    print(f"   MAE rata-rata: {cv_mae.mean():.2f} ± {cv_mae.std():.2f}")
    print(f"   Perbandingan dgn single split Task 2.2 (R2={r2:.3f}): "
          f"{'konsisten' if abs(cv_r2.mean() - r2) < 0.1 else 'terdapat selisih cukup besar -> indikasi overfitting/varians tinggi'}")

    oos_summary = pd.DataFrame({"fold": range(1, 6), "r2": cv_r2, "mae": cv_mae})
else:
    print("\n⚠️ Model prediktif ('model'/X/y dari Task 2.2) tidak ditemukan di memori -> "
          "uji out-of-sample dilewati (hanya relevan untuk komponen yang bersifat prediktif).")
    oos_summary = pd.DataFrame()

# -----------------------------------------------------
# (d) Evaluasi hasil robustness (ringkasan gabungan)
# -----------------------------------------------------
robustness_summary = pd.DataFrame([
    {"uji": "Sensitivitas bobot (Spearman, 1000 sampel)", "metrik": "korelasi rata-rata",
     "nilai": round(np.mean(spearman_vals), 3), "ambang_baik": ">= 0.80",
     "status": "BAIK" if np.mean(spearman_vals) >= 0.80 else "PERLU DICERMATI"},
    {"uji": "Monte Carlo (input+bobot, 1000 iterasi)", "metrik": "rata-rata std rank",
     "nilai": round(buildings["mc_rank_std"].mean(), 1), "ambang_baik": "< 10% N bangunan",
     "status": "BAIK" if buildings["mc_rank_std"].mean() < 0.10 * len(buildings) else "PERLU DICERMATI"},
    {"uji": "Bootstrap komposisi Top-N (500 resample)", "metrik": "indeks Jaccard rata-rata",
     "nilai": round(mean_jaccard, 3), "ambang_baik": ">= 0.60",
     "status": "BAIK" if mean_jaccard >= 0.60 else "PERLU DICERMATI"},
])
if not oos_summary.empty:
    robustness_summary = pd.concat([robustness_summary, pd.DataFrame([{
        "uji": "Out-of-sample CV model ekonomi (5-fold)", "metrik": "R2 rata-rata",
        "nilai": round(cv_r2.mean(), 3), "ambang_baik": ">= 0.60",
        "status": "BAIK" if cv_r2.mean() >= 0.60 else "PERLU DICERMATI",
    }])], ignore_index=True)

print("\n📋 RINGKASAN EVALUASI ROBUSTNESS:")
print(robustness_summary.to_string(index=False))

# ==========================================================
# GRAFIK 5.3 — Uncertainty band Top-20 (Monte Carlo) & CV scores
# ==========================================================
plt.close("all")
n_panels = 3 if not oos_summary.empty else 2
fig5b, axes5b = plt.subplots(1, n_panels, figsize=(6.5 * n_panels, 6))

# Panel 1: Uncertainty band (CI 90%) priority_score, Top-20
ax = axes5b[0]
top20_mc = buildings.nsmallest(TOP_N, "rank").sort_values("mc_score_mean")
ax.errorbar(
    top20_mc["mc_score_mean"], top20_mc["building_id"].astype(str),
    xerr=[
        top20_mc["mc_score_mean"] - top20_mc["mc_score_ci_low"],
        top20_mc["mc_score_ci_high"] - top20_mc["mc_score_mean"],
    ],
    fmt="o", color="#378ADD", ecolor="#A9C9E8", capsize=3,
)
ax.set_xlabel("Priority Score (rata-rata Monte Carlo ± CI 90%)")
ax.set_title(f"Ketidakpastian Priority Score — Top {TOP_N}")
ax.grid(axis="x", alpha=0.2)

# Panel 2: Bootstrap frequency vs Monte Carlo Top-N probability (Top-20)
ax2 = axes5b[1]
comp = buildings.nsmallest(TOP_N, "rank").sort_values("mc_topN_prob")
ax2.barh(comp["building_id"].astype(str), comp["mc_topN_prob"], color="#EF9F27",
          alpha=0.8, label="Monte Carlo (input+bobot)")
ax2.barh(comp["building_id"].astype(str), comp["bootstrap_topN_freq"], color="#1D9E75",
          alpha=0.5, label="Bootstrap (resample data)")
ax2.axvline(STABLE_THRESHOLD, color="#D85A30", linestyle="--", linewidth=1)
ax2.set_xlabel(f"Probabilitas / frekuensi tetap di Top-{TOP_N}")
ax2.set_title("Perbandingan Uji Robustness: Monte Carlo vs Bootstrap")
ax2.legend(fontsize=8)
ax2.grid(axis="x", alpha=0.2)

# Panel 3 (jika ada): Boxplot skor CV model ekonomi
if not oos_summary.empty:
    ax3 = axes5b[2]
    ax3.boxplot([cv_r2, (cv_mae - cv_mae.min()) / (cv_mae.max() - cv_mae.min() + 1e-9)],
                tick_labels=["R2 (5-fold)", "MAE ternormalisasi (5-fold)"])
    ax3.set_title("Out-of-sample CV — Model Economic Value")
    ax3.grid(axis="y", alpha=0.2)

plt.tight_layout()
plt.savefig(f"{OUT_DIR}/output5_robustness_tests.png", dpi=150)
plt.show()
print(f"✅ Grafik uji robustness tersimpan: {OUT_DIR}/output5_robustness_tests.png")

# ==========================================================
# 5.4  IDENTIFIKASI SUMBER KETIDAKPASTIAN
# ==========================================================
print("\n[5.4] IDENTIFIKASI SUMBER KETIDAKPASTIAN")
print("-" * 70)

pct_default_height = 100 * (np.isclose(buildings["height"], 10.0)).sum() / len(buildings)
mean_ci_width = (buildings["mc_score_ci_high"] - buildings["mc_score_ci_low"]).mean()

uncertainty_sources = pd.DataFrame([
    {
        "kategori": "Ketidakpastian data input",
        "sumber": "Resolusi raster GHI/DNI/GTI (~250 m) vs skala footprint bangunan (<100 m2)",
        "dampak_potensial": "Nilai iradiasi per bangunan adalah rata-rata area, bisa kurang akurat "
                             "untuk bangunan kecil/berdekatan",
        "indikasi_kuantitatif": "1 piksel raster dapat mewakili puluhan bangunan sekaligus",
    },
    {
        "kategori": "Ketidakpastian data input",
        "sumber": "Cloud Fraction dari rata-rata 1 tahun (S2 Cloud Probability, 2023-2024)",
        "dampak_potensial": "Tidak menangkap variasi musiman/tahun-ke-tahun; representasi "
                             "shading jangka pendek bisa bias",
        "indikasi_kuantitatif": "Periode observasi hanya 1 tahun",
    },
    {
        "kategori": "Ketidakpastian data input",
        "sumber": "Tinggi bangunan memakai nilai default 10 m jika data asli tidak ada",
        "dampak_potensial": "Estimasi shading & kapasitas panel pada bangunan tanpa data "
                             "tinggi asli menjadi kurang akurat",
        "indikasi_kuantitatif": f"{pct_default_height:.1f}% bangunan memakai nilai default",
    },
    {
        "kategori": "Ketidakpastian struktur model",
        "sumber": "Target 'economic_proxy' bersifat sintetis (bukan data harga/nilai riil)",
        "dampak_potensial": "Model regresi mempelajari hubungan proxy, bukan nilai ekonomi "
                             "aktual -> risiko bias sistematis terhadap definisi proxy",
        "indikasi_kuantitatif": f"R2 out-of-sample rata-rata: "
                                 f"{cv_r2.mean():.3f} ± {cv_r2.std():.3f}" if not oos_summary.empty else "N/A",
    },
    {
        "kategori": "Ketidakpastian struktur model",
        "sumber": "Agregasi Weighted Linear Combination (WLC) mengasumsikan hubungan "
                   "linier & dapat saling menggantikan (fully compensatory) antar indeks",
        "dampak_potensial": "Bangunan dengan satu indeks sangat rendah tetap bisa berprioritas "
                             "tinggi jika indeks lain sangat tinggi, meski scr fisik tidak layak",
        "indikasi_kuantitatif": "Struktural, tidak diukur langsung — mitigasi lihat Task 5.2/5.3",
    },
    {
        "kategori": "Ketidakpastian pembobotan (subjektif)",
        "sumber": "Bobot W_MAIN (PV 40% / Econ 35% / Env 25%) ditentukan berdasarkan "
                   "penilaian ahli/asumsi, bukan hasil optimasi data",
        "dampak_potensial": "Ranking bangunan dapat berubah signifikan pada bangunan "
                             "berperingkat menengah bila bobot berbeda",
        "indikasi_kuantitatif": f"Korelasi Spearman rata-rata thd 1000 bobot acak: "
                                 f"{np.mean(spearman_vals):.3f}",
    },
    {
        "kategori": "Ketidakpastian klasifikasi",
        "sumber": "Kelas prioritas (Rendah/Sedang/Tinggi) berbasis kuantil bergantung "
                   "pada distribusi data saat ini",
        "dampak_potensial": "Ambang batas kelas akan bergeser jika ada penambahan/"
                             "pengurangan data bangunan di masa depan",
        "indikasi_kuantitatif": "Lihat perbandingan kuantil vs breakpoint tetap (Task 4.2)",
    },
    {
        "kategori": "Ketidakpastian sampling/data bangunan",
        "sumber": "Footprint bangunan hasil digitasi/ekstraksi otomatis, berpotensi "
                   "memuat kesalahan geometri atau duplikasi",
        "dampak_potensial": "Skor & ranking pada bangunan dengan geometri bermasalah "
                             "dapat menyesatkan",
        "indikasi_kuantitatif": f"{n_invalid} geometri tidak valid, {n_dup_geom} duplikat "
                                 f"(lihat Task 5.1)",
    },
])

print(uncertainty_sources.to_string(index=False))
uncertainty_sources.to_csv(f"{OUT_DIR}/output5_uncertainty_sources.csv", index=False)
print(f"\n✅ Tabel sumber ketidakpastian tersimpan: {OUT_DIR}/output5_uncertainty_sources.csv")

# ==========================================================
# OUTPUT 5 — SIMPAN SELURUH HASIL TASK 5
# ==========================================================
output5_cols = [
    "building_id", "centroid_lon", "centroid_lat", "priority_score", "rank",
    "rank_delta_mean", "rank_delta_std", "topN_inclusion_prob", "priority_stable",
    "mc_score_mean", "mc_score_ci_low", "mc_score_ci_high",
    "mc_rank_mean", "mc_rank_std", "mc_topN_prob", "bootstrap_topN_freq",
]
output5_cols = [c for c in output5_cols if c in buildings.columns]
output5 = buildings[output5_cols].sort_values("rank")
output5.to_csv(f"{OUT_DIR}/output5_validation_sensitivity_robustness.csv", index=False)

robustness_summary.to_csv(f"{OUT_DIR}/output5_robustness_summary.csv", index=False)
if not oos_summary.empty:
    oos_summary.to_csv(f"{OUT_DIR}/output5_outofsample_cv.csv", index=False)

print("\n✅ OUTPUT 5 tersimpan:")
print(f"   - {OUT_DIR}/output5_data_validation_report.csv")
print(f"   - {OUT_DIR}/output5_validation_sensitivity_robustness.csv")
print(f"   - {OUT_DIR}/output5_robustness_summary.csv")
print(f"   - {OUT_DIR}/output5_uncertainty_sources.csv")
print(f"   - {OUT_DIR}/output5_sensitivity_advanced.png")
print(f"   - {OUT_DIR}/output5_robustness_tests.png")
if not oos_summary.empty:
    print(f"   - {OUT_DIR}/output5_outofsample_cv.csv")

print("\n🎉 TASK 5 SELESAI — Model telah divalidasi (kualitas data & konsistensi spasial), "
      "diuji sensitivitasnya secara sistematis, diuji robustness-nya (Monte Carlo, "
      "bootstrap, out-of-sample CV), dan sumber-sumber ketidakpastiannya teridentifikasi "
      "beserta indikasi besarannya.")

"""**FINAL RESULT MAP**"""

import numpy as np
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
from matplotlib.patches import Patch, FancyArrow

try:
    import contextily as cx
    HAS_CONTEXTILY = True
except ImportError:
    HAS_CONTEXTILY = False
    print("⚠️ 'contextily' belum terinstall -> basemap kontekstual dilewati "
          "(jalankan: !pip install -q contextily lalu ulangi Task 6).")

try:
    import folium
    HAS_FOLIUM = True
except ImportError:
    HAS_FOLIUM = False
    print("⚠️ 'folium' belum terinstall -> peta interaktif dilewati "
          "(jalankan: !pip install -q folium mapclassify lalu ulangi Task 6).")

print("\n" + "=" * 70)
print("🗺️  TASK 6 — PETA KARTOGRAFIS FINAL & PETA INTERAKTIF")
print("=" * 70)

DATA_SOURCE_TEXT = (
    "Sumber: Global Solar Atlas (GHI/DNI/GTI) | Sentinel-2 Cloud Probability (S2CLOUDLESS) | "
    "OpenStreetMap (jaringan jalan & POI) | GISACT Building Footprint\n"
    "Proyeksi: UTM 49S (EPSG:32749) | Basemap: CartoDB Positron"
)

# --- Siapkan GeoDataFrame keluaran (pakai 'output4' bila ada, fallback ke 'buildings') ---
gdf_final = output4.copy() if "output4" in globals() else buildings.copy()
gdf_final = gpd.GeoDataFrame(gdf_final, geometry="geometry", crs=buildings.crs)

# Proyeksikan ke CRS meter (UTM) agar skala batang & basemap akurat secara metrik
gdf_utm = gdf_final.to_crs(UTM_CRS)

# ==========================================================
# 6.1  FUNGSI UTILITAS KARTOGRAFI (skala batang & arah mata angin)
# ==========================================================

def add_scale_bar(ax, location=(0.04, 0.04), length_fraction=0.25, color="black"):
    """Skala batang sederhana, dihitung otomatis ke angka 'bulat' terdekat
    (mis. 200 m / 500 m / 1 km) berdasarkan lebar peta saat ini (CRS meter)."""
    xlim, ylim = ax.get_xlim(), ax.get_ylim()
    width = xlim[1] - xlim[0]
    raw_len = width * length_fraction
    magnitude = 10 ** np.floor(np.log10(raw_len))
    nice_len = round(raw_len / magnitude) * magnitude

    x0 = xlim[0] + width * location[0]
    y0 = ylim[0] + (ylim[1] - ylim[0]) * location[1]

    ax.plot([x0, x0 + nice_len], [y0, y0], color=color, lw=4, solid_capstyle="butt", zorder=10)
    ax.plot([x0, x0], [y0 - width * 0.005, y0 + width * 0.005], color=color, lw=1.5, zorder=10)
    ax.plot([x0 + nice_len, x0 + nice_len], [y0 - width * 0.005, y0 + width * 0.005],
            color=color, lw=1.5, zorder=10)

    label = f"{nice_len / 1000:.1f} km" if nice_len >= 1000 else f"{nice_len:.0f} m"
    ax.text(x0 + nice_len / 2, y0 + width * 0.012, label, ha="center", va="bottom",
             fontsize=9, fontweight="bold", zorder=10)


def add_north_arrow(ax, location=(0.94, 0.90), size=0.045):
    """Arah mata angin (panah + huruf N) di pojok kanan-atas peta."""
    x, y = location
    ax.annotate(
        "N", xy=(x, y), xytext=(x, y - size), xycoords="axes fraction",
        textcoords="axes fraction", ha="center", va="center", fontsize=13, fontweight="bold",
        arrowprops=dict(facecolor="black", edgecolor="black", width=4, headwidth=11, headlength=10),
        zorder=10,
    )

# ==========================================================
# 6.2  PETA STATIS 1 — PRIORITY SCORE (choropleth kuantitatif)
#      Skema warna: sequential ColorBrewer 'YlOrRd' (bukan rainbow/jet;
#      tepat utk data kuantitatif ber-urutan rendah->tinggi)
# ==========================================================
plt.close("all")
fig6a, ax6a = plt.subplots(figsize=(12, 10))

gdf_utm.plot(
    column="priority_score", cmap="YlOrRd", ax=ax6a,
    edgecolor="#4d4d4d", linewidth=0.15,
    legend=True,
    legend_kwds={"label": "Priority Score (0 = terendah, 1 = tertinggi)", "shrink": 0.6},
)

if HAS_CONTEXTILY:
    try:
        cx.add_basemap(ax6a, crs=gdf_utm.crs.to_string(), source=cx.providers.CartoDB.Positron)
    except Exception as e:
        print(f"⚠️ Basemap gagal dimuat ({e}) -> peta tetap dilanjutkan tanpa basemap.")

# Highlight Top-20 dengan outline mencolok (tetap dgn palet non-rainbow)
top20_gdf_utm = gdf_utm.nsmallest(20, "rank")
top20_gdf_utm.boundary.plot(ax=ax6a, color="#2166ac", linewidth=1.3, zorder=6)

add_scale_bar(ax6a)
add_north_arrow(ax6a)

ax6a.set_title(
    "Peta Prioritas Pemasangan Solar PV per Bangunan\n"
    "(Outline biru = Top 20 bangunan prioritas tertinggi)",
    fontsize=14, fontweight="bold", pad=12,
)
ax6a.set_xlabel("")
ax6a.set_ylabel("")
ax6a.set_xticks([])
ax6a.set_yticks([])
ax6a.text(
    0.01, -0.06, DATA_SOURCE_TEXT, transform=ax6a.transAxes,
    fontsize=7.5, va="top", ha="left", color="#333333",
)

plt.tight_layout()
plt.savefig(f"/content/drive/MyDrive/GISACT/output6_priority_score_map_final.png", dpi=300, bbox_inches="tight")
plt.show()
print(f"✅ Peta kartografis Priority Score tersimpan (300 dpi): "
      f"/content/drive/MyDrive/GISACT/output6_priority_score_map_final.png")

# ==========================================================
# 6.3  PETA STATIS 2 — KLASIFIKASI PRIORITAS (kategorikal)
#      Skema warna: diverging 3-kelas ColorBrewer 'RdYlBu' (dibalik),
#      ramah buta warna & kontras jelas antar kelas (bukan rainbow acak)
# ==========================================================
plt.close("all")
fig6b, ax6b = plt.subplots(figsize=(12, 10))

# Palet 3-kelas ColorBrewer (RdYlBu, dibalik agar 'Tinggi' = merah/hangat)
class_colors_cb = {"Rendah": "#2c7bb6", "Sedang": "#ffffbf", "Tinggi": "#d7191c"}
gdf_utm["_color"] = gdf_utm["priority_class"].map(class_colors_cb)

gdf_utm.plot(color=gdf_utm["_color"], ax=ax6b, edgecolor="#4d4d4d", linewidth=0.15)

if HAS_CONTEXTILY:
    try:
        cx.add_basemap(ax6b, crs=gdf_utm.crs.to_string(), source=cx.providers.CartoDB.Positron)
    except Exception as e:
        print(f"⚠️ Basemap gagal dimuat ({e}) -> peta tetap dilanjutkan tanpa basemap.")

legend_elements = [Patch(facecolor=c, edgecolor="#4d4d4d", label=k) for k, c in class_colors_cb.items()]
ax6b.legend(handles=legend_elements, loc="upper right", title="Kelas Prioritas",
            fontsize=10, title_fontsize=11, frameon=True)

add_scale_bar(ax6b)
add_north_arrow(ax6b)

ax6b.set_title("Peta Klasifikasi Prioritas Solar PV per Bangunan", fontsize=14, fontweight="bold", pad=12)
ax6b.set_xlabel("")
ax6b.set_ylabel("")
ax6b.set_xticks([])
ax6b.set_yticks([])
ax6b.text(
    0.01, -0.06, DATA_SOURCE_TEXT, transform=ax6b.transAxes,
    fontsize=7.5, va="top", ha="left", color="#333333",
)

plt.tight_layout()
plt.savefig(f"/content/drive/MyDrive/GISACT/output6_priority_class_map_final.png", dpi=300, bbox_inches="tight")
plt.show()
print(f"✅ Peta kartografis Klasifikasi Prioritas tersimpan (300 dpi): "
      f"/content/drive/MyDrive/GISACT/output6_priority_class_map_final.png")

# ==========================================================
# 6.4  PETA INTERAKTIF (WEB MAP) — pendamping peta statis
# ==========================================================
if HAS_FOLIUM:
    print("\n[6.4] Menyusun peta interaktif (web map)...")

    gdf_wgs = gdf_final.to_crs("EPSG:4326")
    popup_cols = [c for c in [
        "building_id", "pv_index", "econ_index", "env_index",
        "priority_score", "rank", "priority_class",
    ] if c in gdf_wgs.columns]

    center = [gdf_wgs.geometry.centroid.y.mean(), gdf_wgs.geometry.centroid.x.mean()]

    # --- Layer 1: Priority Score (choropleth kuantitatif, sequential YlOrRd) ---
    m = gdf_wgs.explore(
        column="priority_score",
        cmap="YlOrRd",
        legend=True,
        legend_kwds={"caption": "Priority Score"},
        tooltip=popup_cols,
        popup=popup_cols,
        style_kwds={"weight": 0.4, "fillOpacity": 0.75},
        name="Priority Score",
        tiles="CartoDB positron",
        location=center,
        zoom_start=14,
        control_scale=True,
    )

    # --- Layer 2: Klasifikasi Prioritas (kategorikal, palet ColorBrewer sama dgn peta statis) ---
    m = gdf_wgs.explore(
        m=m,
        column="priority_class",
        cmap=["#2c7bb6", "#ffffbf", "#d7191c"],  # urut sesuai kategori Rendah/Sedang/Tinggi
        categorical=True,
        legend=True,
        legend_kwds={"caption": "Kelas Prioritas"},
        tooltip=popup_cols,
        popup=popup_cols,
        style_kwds={"weight": 0.4, "fillOpacity": 0.75},
        name="Kelas Prioritas",
        show=False,  # non-aktif secara default, bisa dinyalakan via layer control
    )

    # --- Layer 3: Top-20 bangunan prioritas (outline highlight) ---
    top20_wgs = gdf_wgs.nsmallest(20, "rank")
    m = top20_wgs.boundary.explore(
        m=m, color="#2166ac", style_kwds={"weight": 3},
        name="Outline Top-20 Prioritas", show=True,
    )

    folium.LayerControl(collapsed=False).add_to(m)

    title_html = (
        '<div style="position: fixed; top: 10px; left: 60px; z-index: 9999; '
        'background: white; padding: 8px 14px; border-radius: 6px; '
        'box-shadow: 0 1px 4px rgba(0,0,0,0.3); font-size: 15px; font-weight: bold;">'
        'Peta Interaktif Prioritas Solar PV — GISACT</div>'
    )
    m.get_root().html.add_child(folium.Element(title_html))

    source_html = (
        f'<div style="position: fixed; bottom: 10px; left: 10px; z-index: 9999; '
        f'background: rgba(255,255,255,0.85); padding: 5px 10px; border-radius: 4px; '
        f'font-size: 10px; max-width: 420px;">{DATA_SOURCE_TEXT.replace(chr(10), "<br>")}</div>'
    )
    m.get_root().html.add_child(folium.Element(source_html))

    webmap_path = f"{OUT_DIR}/output6_interactive_webmap.html"
    m.save(webmap_path)
    print(f"✅ Peta interaktif (web map) tersimpan: {webmap_path}")
    print("   Berisi 3 layer (Priority Score, Kelas Prioritas, Outline Top-20), "
          "dgn tooltip/popup per-bangunan, basemap CartoDB Positron, & kontrol layer.")
else:
    print("\n[6.4] Peta interaktif dilewati karena 'folium' tidak tersedia.")

print("\n🎉 TASK 6 SELESAI — Peta keluaran akhir disusun mengikuti kaidah kartografi "
      "(skema warna sequential/diverging ColorBrewer, legenda, skala batang, arah mata "
      "angin, sumber data, basemap kontekstual), dilengkapi peta interaktif (web map) "
      "sebagai pendamping peta statis resolusi tinggi (300 dpi).")